### ISSUE TITLE
fatal error: matrixops_2D.h: No such file or directory

### ISSUE THREAD

**Issue by Toeplitz** [ahay/src#103]
I believe this commit: 
https://github.com/ahay/src/commit/9951fcbd185333e16126f91a5a45ad92f92ad134

has introduces the error of missing matrixops_2D.h:

build/user/zone/gendix.c:24:26: fatal error: matrixops_2D.h: No such file or directory

**Comment by sfomel** [comment]
I believe this is resolved.
