### ISSUE TITLE
Docker Build

### ISSUE THREAD

**Issue by jdrew99** [ahay/src#109]
## Feature / Proposal:

Maintain a "Dockerfile" and build of Madagascar on DockerHub. Attached is an example of a first version build; this could do with some improvements / cleanup. This example has been pushed to DockerHub as "jdrew/madagascar".

[Dockerfile.zip](https://github.com/ahay/src/files/490854/Dockerfile.zip)

**Note**: for those not familiar with DockerHub: Auto-Build requires an account (free) linked to a GitHub project, where the Dockerfile (build script) is hosted. [**Link to DockerHub**](https://docs.docker.com/docker-hub/builds)

I am not familiar yet on how best to configure this, whether to include the "Dockerfile" in "ahay/src" or as a separate GitHub project.

**Comment by kschleicher** [comment]
jdrew,

I saved your email from 18 month ago about using docker for Madagascar.  I have finally got back to this topic.  It would be helpful in our Madagascar schools and working workshops.  It comes up in discussions from time to time.  I have finally got to this topics, but I have never worked with dockers.  I do not know if you are still interested and willing to help.  We are interested to see if we can use dockers at the working workshop in August:

http://www.ahay.org/wiki2015/index.php?title=HoustonWW2018


I do not want to go too far into the details of my efforts before finding out if you still have are interested I will write a little. This will help me remember where I am.

I ran:

docker run -it jdrew/madagascar /bin/bash

and discovered a version of Madagascar that seems to run, but I could not get display back to the screen.


When sending displays to screen using xtpen I get:

Error: Can't open display:


I tried to follow step by step instructions at:

https://forums.docker.com/clicks/track?url=https%3A%2F%2Ffredrikaverpil.github.io%2F2016%2F07%2F31%2Fdocker-for-mac-and-gui-applications%2F&post_id=32650&topic_id=17797

with little success.  The above site suggested things like:

docker run -it -e DISPLAY=$DISPLAY jdrew/madagascar /bin/bash


There were also instructions on adding host + or changing Quartz preferences to allow other hosts to send x to computer



Regards,

Karl Schleicher



________________________________

**Comment by sfomel** [comment]
Implemented in https://github.com/ahay/src/tree/master/admin/docker
