### ISSUE TITLE
Installation failing due to lack of Qfwi_modeling.h dependency

### ISSUE THREAD

**Issue by ishiikurisu** [ahay/src#114]
After cloning this repository to my local computer, I tried to install it on my computer. After running `configure --prefix=/somewhere/in/my/notebook`, I tried to run `make`, but the  installation fails with the following error:

```
scons: *** [build/user/jsun/mpipfwi.py] Implicit dependency `build/user/jsun/Qfwi_modeling.h' not found, needed by target `build/user/jsun/mpipfwi.py'.
```

Why?

**Comment by stefanofiorentino** [comment]
If you don't need jsun's work, then remove that user's directory and retry
compiling

Il giorno lun 16 gen 2017 alle 18:36 Cris Silva Jr. <
notifications@github.com> ha scritto:

**Comment by ishiikurisu** [comment]
I removed jsun and zone, it compiled well here. I will do more tests later and check if there are further problems. Thank you!
