### ISSUE TITLE
Numeric errors are encountered when reading float number by using Python API 

### ISSUE THREAD

**Issue by lingfengfly** [ahay/src#118]
I write a python script using Python API to do some tasks. It can read float parameters from command-line. It looks like this (I omit the calculation part.) : 
```
import rsf.api as rsf
import numpy as np

# pars from command line
par = rsf.Par()
o11 = par.float('o1',0) #z0
o22 = par.float('o2',0) #x0
o33 = par.float('o3',0) #y0

d11 = par.float('d1',1) #dz
d22 = par.float('d2',1) #dx
d33 = par.float('d3',1) #dy

n11 = par.int('n1',1) #nz
n22 = par.int('n2',1) #nx
n33 = par.int('n3',1) #ny

#some calculations
data=np.abs(2)

print d11
print d22
print d33

output=rsf.Output()
output.put('o1',o11)
output.put('o2',o22)
output.put('o3',o33)
output.put('n1',n11)
output.put('n2',n22)
output.put('n3',n33)
output.put('d1',d11)
output.put('d2',d22)
output.put('d3',d33)
output.write(data) 
```
I name this program "sftestin". And I use it through the terminal like this: 
```
sftestin  o1=0 d1=0.1 n1=201 o2=108 d2=0.125 n2=151 o3=34 d3=0.35 n3=15 >test.rsf 
```
Then, the head of output file 'test.rsf' is 
``` 
0.10000000149
0.125
0.34999999404
2.1-git	sftestin	home/test/:	s@s-r	Sun Jul 16 19:45:42 2017

	d2=0.125
	n2=151
	o1=0
	d3=0.35
	n3=15
	o2=108
	data_format="native_float"
	o3=34
	esize=4
	in="./test.rsf@"
	d1=0.1
	n1=201
```
The value of 'd11' and 'd33' are 0.10000000149 and 0.34999999404, respectively, and they change the values when the program running. However, I set them as 0.1 and 0.35 in the command-line, and the values in output file seem right (d1=0.1 d3=0.35). 
I try to modify the Python file 'api.py' by just adding a line like this:
```
import rsf.doc
import rsf.prog
import rsf.path

###
#just add a line in the following
_swig_ = False
(...)
```
And run the program again. And the output seem correct.
The head of output file:
```
0.1
0.125
0.35
To use Output, you need to install SWIG http://www.swig.org/
```
It seems like relating to the c library. My Madagascar version is the latest version (2.0-1). And I tested in version 1.7, it has the same errors.

**Comment by kschleicher** [comment]
This looks like a difference in rounding.  Python floats are usually double precision.  C floats are usually single precision.  .125 has an exact binary presentation, so there is no rounding.  The other numbers are accurate to 8 digits, the accuracy of single precision.

Karl Schleicher


________________________________

**Comment by lingfengfly** [comment]
Hi, Karl Schleicher
Thank you for your reply. I understand what you mean. But how can I fix this problem, i.e., let the value of parameters in the Python program be exactly same as the command-line? 
Because I need use different values of these parameters to do some calculate tasks. If I can pass the parameters through the command-line, it will be useful and convenient for me.

**Comment by kschleicher** [comment]
lingfeng,

I am not sure how to answer this, so please forgive me if I say things you already know well.



There will be some rounding when you use floating point numbers.  When you compute the range of z values from

o1=0 d1=0.1 n1=201

You expect to get 0.0 to 20.0, but you get 0.0 to 20.000000298.  You need to write your code to tolerate this.  If you expect the last value to be expected_last=20.0 and you compute computed_last=20.000000298 comparison will not be as expected. for example:

computed_z=0
while computed_z<=20.0 :
    do something
    computed_z+=delta_z

will not process the last point.  A better practice is:

for indx_z in range(n1):
    computed_z=indx_z*delta_z
    do something

Karl Schleicher




________________________________
