### ISSUE TITLE
stack.diffimg sffocus failure at max iterations

### ISSUE THREAD

**Issue by rjdelf** [ahay/src#121]
Not sure this is a bug or just me but I'm running the [stack.diffimg](http://ahay.org/rsf_epydoc/rsf.recipes.stack-pysrc.html#diffimg) script to extract diffractions using near-offset data similar to [this example](http://ahay.org/RSF/book/tccs/diffr/paper_html/node6.html). The sffocus step does not converge sufficiently to terminate (with relatively large smoothing values), and at the default max of 100 iterations does the following and crashes;
> .
> .
> .
> sffocus: iteration 95 res: 0.106927 grad: 0.000042
> sffocus: iteration 96 res: 0.106925 grad: 0.000038
> sffocus: iteration 97 res: 0.106926 grad: 0.000033
> sffocus: iteration 98 res: 0.106925 grad: 0.000027
> sffocus: iteration 99 res: 0.106926 grad: 0.000022
> sffocus: iteration 0 res: 0.921149 grad: 0.000000
> sffocus: convergence in 1 iterations, alpha=7.30603e-11, gd=7.30603e-11
> sfcut: build/api/c/alloc.c: illegal allocation (0 bytes)
> scons: *** [tel-foc.rsf] Error 1
> scons: building terminated because of errors.

Would it be possible to assign a max iteration when the stack.diffimg program is called?

**Comment by sfomel** [comment]
It looks like it crashes at sfcut.

` '''
cut max1=%g | cut min1=%g  
 ''' % (frect1,frect2,tmin,tmax) `

You may want to check tmin and tmax parameters to make sure they are in the range of your data.

**Comment by rjdelf** [comment]
My apologies, thanks for spotting that! Works fine when I bumped tmax down a bit.
Thanks,
Richard
