### ISSUE TITLE
xtpen error when compiling in Mac OS High Sierra 

### ISSUE THREAD

**Issue by tmdao** [ahay/src#122]
Hello,

I'm trying to compile the new version of Madagascar in the newest Mac OS but there's an error (so far) with xtpen.c file. The returned error is pasted after the dashed line. 

--------------------------------------------------------------------------------

clang -o build/pens/main/xtpen.o -c -O2 -Ibuild/include -I/opt/local/include -I/opt/X11/include build/pens/main/xtpen.c
build/pens/main/xtpen.c:218:13: error: expected parameter declarator
extern void bcopy (const void *src, void *dst, size_t len);
            ^
/usr/include/secure/_strings.h:46:52: note: expanded from macro 'bcopy'
                __builtin___memmove_chk (dest, src, __VA_ARGS__, __darwin_obsz0 (dest))
                                                                 ^
/usr/include/secure/_common.h:38:63: note: expanded from macro '__darwin_obsz0'
#define __darwin_obsz0(object) __builtin_object_size (object, 0)
                                                              ^
build/pens/main/xtpen.c:218:13: error: expected ')'
/usr/include/secure/_strings.h:46:52: note: expanded from macro 'bcopy'
                __builtin___memmove_chk (dest, src, __VA_ARGS__, __darwin_obsz0 (dest))
                                                                 ^
/usr/include/secure/_common.h:38:63: note: expanded from macro '__darwin_obsz0'
#define __darwin_obsz0(object) __builtin_object_size (object, 0)
                                                              ^
build/pens/main/xtpen.c:218:13: note: to match this '('
/usr/include/secure/_strings.h:46:52: note: expanded from macro 'bcopy'
                __builtin___memmove_chk (dest, src, __VA_ARGS__, __darwin_obsz0 (dest))
                                                                 ^
/usr/include/secure/_common.h:38:54: note: expanded from macro '__darwin_obsz0'
#define __darwin_obsz0(object) __builtin_object_size (object, 0)
                                                     ^
build/pens/main/xtpen.c:218:13: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
extern void bcopy (const void *src, void *dst, size_t len);
            ^
/usr/include/secure/_strings.h:46:52: note: expanded from macro 'bcopy'
                __builtin___memmove_chk (dest, src, __VA_ARGS__, __darwin_obsz0 (dest))
                                                                 ^
/usr/include/secure/_common.h:38:32: note: expanded from macro '__darwin_obsz0'
#define __darwin_obsz0(object) __builtin_object_size (object, 0)
                               ^
build/pens/main/xtpen.c:218:13: error: conflicting types for '__builtin___memmove_chk'
/usr/include/secure/_strings.h:46:3: note: expanded from macro 'bcopy'
                __builtin___memmove_chk (dest, src, __VA_ARGS__, __darwin_obsz0 (dest))
                ^
build/pens/main/xtpen.c:218:13: note: '__builtin___memmove_chk' is a builtin with type 'void *(void *,
      const void *, unsigned long, unsigned long)'
/usr/include/secure/_strings.h:46:3: note: expanded from macro 'bcopy'
                __builtin___memmove_chk (dest, src, __VA_ARGS__, __darwin_obsz0 (dest))
                ^
1 warning and 3 errors generated.
scons: *** [build/pens/main/xtpen.o] Error 1
scons: building terminated because of errors.

**Comment by sfomel** [comment]
I believe this has been fixed: https://github.com/ahay/src/commit/94f8bdf44a99880cf90266c9933b0a8ff3bb2396
Please try again.

**Comment by tmdao** [comment]
hi Sergey, the issue was indeed fixed. Thank you.
