### ISSUE TITLE
MacOS High Sierra installation with Anaconda 2 

### ISSUE THREAD

**Issue by tmdee** [ahay/src#124]
Hi,

I had to upgrade my OS for my macbook to the latest OS, High Sierra. I have Anaconda 2 installed on the system. I went ahead and compiled Madagascar again as I had done it before. I had my user folder with my own codes there. Everything compiled ok with no returned errors. I changed the bash file to source the Madagascar environment variables file under RSFROOT/share/.../env.sh, added the path to the binary, etc .... So it was standard and I didn't have any problem as I had done it many times before.

However, when I try to see if I could print out the man page for let say "sfin", I got an error saying rsf.prog is not found, and indeed prog wasn't in the site-packages for python for madagascar. I started python and listed the sites, and all folders for python to look for external packages were listed there.

Further problem shooting showed that quite a few programs under my use folder didn't get compiled even though they were all specified in the SConstruct file in my user folder. So I tried to compile everything again on a Ubuntu machine, and it worked just like before.

Are you aware of this issue and do you know anyway to get around it? 

Thank you very much.

tm

**Comment by sfomel** [comment]
Please check PYTHONPATH environmental variable by running "printenv PYTHONPATH".  This is where Madagascar's python packages should be installed, but sometimes different versions of python conflict.
