### ISSUE TITLE
About building madagascar from sources in a virtual machine enviroment

### ISSUE THREAD

**Issue by kenangogogo** [ahay/src#129]
Hello,guys:
       I am building madagascar from sources, and my system is ubuntu which is running in a virtual machine
enviroment. There is an error happend when building, the info is as follows:
      Install file: "build/plot/test/vpplot.py" as "build/framework/rsf/vpplot.py"
      scons:***[build/framework/rsf/prog.py]  Source 'build/framework/rsf/sfmain.py' not found, needed by target 'build/framework/rsf/prog.py'.
     It seems that i missed the file "sfmain.py" in the "build/framework/rsf" directory, but i found that the directory "build/framework/rsf" doesn't contain that file originally. So i have no idea what i shoud do for correcting this error.
    Any suggestion will be appreciated!

**Comment by kschleicher** [comment]
kenangogogo,

I do not know a lot about this file, but the build directory is created when you run:

scons install

 If I remove build/framework/rsf/sfmain.py and run scons install,  I get a lot of print that ends with:


File "/Users/karl/RSFSRC/build/api/python/SConstruct", line 89, in <module>
scons: done reading SConscript files.
scons: Building targets ...
Install file: "build/system/main/sfmain.py" as "build/framework/rsf/sfmain.py"
scons: `install' is up to date.
scons: done building targets.

After the install the file is recreated and I can find the locations that have sfmain.py.

find . -name sfmain.py

./build/framework/rsf/sfmain.py

./build/system/main/sfmain.py

./lib/python2.7/site-packages/rsf/sfmain.py

The full print is in the attached file.

I run on Mac, with a configure command:


./configure CC=clang CXX=clang++ API=f90,python --prefix=`pwd`

on Ubuntu you might use:

./configure API=f90,python --prefix='pwd'

Do you have python 2 installed?

I hope this helps.

Karl Schleicher

________________________________

**Comment by kenangogogo** [comment]
Thanks a lot, Actually, my python version is 3.6.1, and i revised a lot of files because of the incompatibility between python2 and python3.  Moreover, the building process  i adopted is
the way recommended by the madagascar official website, firstly, "./configure --prefix ="location
of RSFRoot", and then "make install", here is different with your step "scons install". Could it be 
this reason for my error message?
     Thanks again for your reply.

**Comment by zhichenggeng** [comment]
Hi, 

I recommend you to install Madagascar using python2. Although scons starts to support python3 in their latest version, some python files in Madagascar don’t support python3.
I suggest you create a python2 environment using anaconda, which is what I did to solve this problem.
Hope it can help you.

**Comment by zhichenggeng** [comment]
Yeah. The same. I used the latest version to construct the source codes, but it failed. I suggest you use the default scons.
