### ISSUE TITLE
Importing data fromrsf file to numpy array

### ISSUE THREAD

**Issue by tgautam03** [ahay/src#130]
I have 3 dimentional hypercube(rsf) and want to import that into a 3 dimentional numpy array. I can't find any way to do that

**Comment by sfomel** [comment]
You can use the Python interface to Madagascar http://www.ahay.org/wiki/Guide_to_madagascar_API#Python_interface

`import os, numpy, m8r
os.system('sfspike n1=5 n2=5 n3=5 k1=3 > spike.rsf')
f = m8r.Input('spike.rsf')
a = numpy.zeros((3,5,5),dtype='float32')
f.read(a)`

**Comment by TusharIITR03** [comment]
import m8r as sf
import numpy as np
import tensorflow as tf
import os
s=sf.Input('a.rsf')
p=sf.Input('b.rsf')
x=np.zeros((1500,1,1),dtype='float32')
y=np.zeros((1500,600,1),dtype='float32')
s.read(x)
p.read(y)

I wrote the following code and the error i am getting is 
AttributeError: 'Input' object has no attribute 'read'

**Comment by TusharIITR03** [comment]
I have also installed swig using madagascar. When I open config.py there's written SWIG=None.
I tried changing None to the path where I have swig installed 
( SWIG = ['/home/seismic5/anaconda2/bin/swig'] )
 but nothing is working
I still get 
 AttributeError: 'Input' object has no attribute 'read'
or
ImportError: No module named c_m8r (when i use c_m8r instead of m8r)

**Comment by TusharIITR03** [comment]
I have also installed swig using madagascar. When I open config.py there's written SWIG=None.
I tried changing None to the path where I have swig installed 
( SWIG = ['/home/seismic5/anaconda2/bin/swig'] )
 but nothing is working
I still get 
 AttributeError: 'Input' object has no attribute 'read'
or
ImportError: No module named c_m8r (when i use c_m8r instead of m8r)

**Comment by kschleicher** [comment]
Tushar03,

Madagascar runs with python2.  You are asking for tensor flow, so I bet you are running python 3.  We need to update.  I am not sure the minimal way to get madagaasscar and provide m8r in python 3.


To test if this is a python2/3 problem, I modified your code to:

import m8r as sf
import numpy as np

import os
s=sf.Input('cmp368.rsf')
p=sf.Input('cmp251.rsf')
x=np.zeros((3000,12),dtype='float32')
y=np.zeros((3000,12),dtype='float32')
s.read(x)
p.read(y)
print x[1000:1010,2]

I have files cdp251.rsf and cmp386.rsf.
When I run with python2 I get:

Macintosh-4:line31-81-m8r karl$ python test.py

[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00

   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00

   0.00000000e+00  -3.24407001e-10]



________________________________

**Comment by TusharIITR03** [comment]
Tensorflow is there for python 2 and I have installed just python 2. My other ml programs run just fine. The problem that I'm facing is with .read(). I have installed swig but in config.py that shows swig=None. I installed swig using anaconda. I just don't know how to fix that.

**Comment by TusharIITR03** [comment]
@kschleicher can you please post the screenshot of your config.py file. Or if you can help me with defining SWIG.

**Comment by kschleicher** [comment]
Tushar03,

On my Mac I had to copy /opt/local/bin/swig to /usr/local/bin/swig before running config.  I've mostly used a mac for about 5 years and I do not remember if I used swig on linux.  Attached is my config.py

Karl



________________________________

**Comment by TusharIITR03** [comment]
I'm sorry I am new to linux. By this do you mean that I copy all the files of SWIG(that i have installed separately) to /usr/local/bin/swig and then run ./configure??

**Comment by TusharIITR03** [comment]
![screenshot from 2018-06-12 12-00-27](https://user-images.githubusercontent.com/30533136/41273828-b066e95a-6e38-11e8-9c4a-93a1b8a47eb3.png)
I have defined SWIG but I'm getting same error.
I am stuck very badly on this from past 4 days.
I just can't import rsf data to numpy.

**Comment by TusharIITR03** [comment]
This is the exact code that i have written:
import m8r as sf
import numpy as np
s=sf.Input('a.rsf')
p=sf.Input('p.rsf')
p1=np.zeros((1500,1,1),dtype='float32')
v1=np.zeros((1500,600,1),dtype='float32')

s.read(v1)
p.read(p1)
THE ERROR THAT I GET IS:
AttributeError: 'Input' object has no attribute 'read'

**Comment by nicklinyi** [comment]
Hi, @TusharIITR03 . I think the reason that you fail to run this piece of code is that you didn't install the python API at the first place. Try configure it with the next line, and reinstall the Madagascar. Then run your code again. I hope this could fix your problem.
```
./configure API=c++,f90,python --prefix=/home/lloyd/rsf2.0
```
BTW, this is the result of a sucessful run. 
```
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import m8r as sf
>>> import numpy as np
>>> import os
>>> s = sf.Input('a.rsf')
>>> p = sf.Input('b.rsf')
>>> x = np.zeros((1500,1,1),dtype='float32')
>>> y = np.zeros((1500,600,1),dtype='float32')
>>> s.read(x)
>>> x
array([[[ 0.]],

       [[ 0.]],

       [[ 1.]],

       ..., 
       [[ 0.]],

       [[ 0.]],

       [[ 0.]]], dtype=float32)
>>> p.read(y)
```

**Comment by kschleicher** [comment]
This is probable correct.  My recommendation is for Mac only.
Karl Schleicher


Sent from my iPhone

On Jun 12, 2018, at 3:20 AM, Yi Lin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, @TusharIITR03<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTusharIITR03&data=02%7C01%7C%7Cdbc7e8ac0f6d44109dea08d5d03d6747%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636643884500474897&sdata=e1NVeC%2FlWuTfl0ykoD4xeU5YOFWlblZFPHzd7tn2OvQ%3D&reserved=0> . I think the reason that you fail to run this piece of code is that you didn't install the python API at the first place. Try configure it with the next line, and reinstall the Madagascar. Then run your code again. I hope this could fix your problem.

./configure API=c++,f90,python --prefix=/home/lloyd/rsf2.0


BTW, this is the result of a sucessful run.

Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import m8r as sf
>>> import numpy as np
>>> import os
>>> s = sf.Input('a.rsf')
>>> p = sf.Input('b.rsf')
>>> x = np.zeros((1500,1,1),dtype='float32')
>>> y = np.zeros((1500,600,1),dtype='float32')
>>> s.read(x)
>>> x
array([[[ 0.]],

       [[ 0.]],

       [[ 1.]],

       ...,
       [[ 0.]],

       [[ 0.]],

       [[ 0.]]], dtype=float32)

**Comment by kschleicher** [comment]
No. My recommendation about copy is Apple Mac OS X only.  Send your ./configure command input and the resulting config.py.  I am away from computer and cannot help much, but I am very interested in your issue.
Karl

Sent from my iPhone

On Jun 12, 2018, at 12:33 AM, Tushar03 <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm sorry I am new to linux. By this do you mean that I copy all the files of SWIG(that i have installed separately) to /usr/local/bin/swig and then run ./configure??

**Comment by TusharIITR03** [comment]
![image](https://user-images.githubusercontent.com/30533136/41333554-da8cf5d6-6eff-11e8-8cb0-15b60e344a9e.png)
I reinstalled madagascar and configured it the way @nicklinyi  asked. Now it doesnot recognize numpy as well. I have attached the config.py
And I'm also not getting sfpen command.

**Comment by TusharIITR03** [comment]
![image](https://user-images.githubusercontent.com/30533136/41334917-b8733e42-6f04-11e8-91af-4112162f4578.png)
this is the output of ./configure @kschleicher

**Comment by nicklinyi** [comment]
Hi, @TusharIITR03 . I wrote a blog about how to install Madagascar correctly in Chinese (http://nickwhyy.top/madagascar/ ). But you can just follow the code in the post to install it in your machine. I think it might be helpful somehow. Moreover it will be very helpful if you the exact step of how you install the Madagascar package (every command and its result). Thanks.

**Comment by TusharIITR03** [comment]
@nicklinyi  I followed the instructions provided by you and it worked.
Thanks a lot...

**Comment by LinRoyalle** [comment]
> ```python
> import os, numpy, m8r
> os.system('sfspike n1=5 n2=5 n3=5 k1=3 > spike.rsf')
> ```

but

> You can use the [Python interface to Madagascar ](http://www.ahay.org/wiki/Guide_to_madagascar_API#Python_interface)
> 
> ```python
> import os, numpy, m8r
> os.system('sfspike n1=5 n2=5 n3=5 k1=3 > spike.rsf')
> f = m8r.Input('spike.rsf')
> a = numpy.zeros((3,5,5),dtype='float32')
> f.read(a)
> ```

When i use os.systm('sfspike n1=5 n2=5 n3=5 k1=3 > spike.rsf'), it will tell me sfspike not found. How to deal with it
