### ISSUE TITLE
Problem while run "make install" with Madagascar on Cygwin.

### ISSUE THREAD

**Issue by RosendOcana** [ahay/src#131]
$ make; sudo make install
RSFROOT=/usr PYTHONPATH=/usr/lib/python2.7/site-packages /usr/bin/scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `build/framework/rsf' is up to date.
scons: `build/framework/doc' is up to date.
scons: `build/framework/ptools' is up to date.
scons: `build/book/Recipes' is up to date.
scons: `build/book/gallery' is up to date.
scons: `build/include' is up to date.
scons: `build/lib' is up to date.
scons: `build/api/c' is up to date.
scons: `build/api/python' is up to date.
scons: `build/api/julia' is up to date.
scons: `build/api/c++' is up to date.
scons: `build/system/generic' is up to date.
scons: `build/system/main' is up to date.
scons: `build/system/seismic' is up to date.
scons: `build/user/aklokov' is up to date.
scons: `build/user/bash' is up to date.
scons: `build/user/browaeys' is up to date.
scons: `build/user/chen' is up to date.
scons: `build/user/chengjb' is up to date.
scons: `build/user/chenyk' is up to date.
scons: `build/user/cram' is up to date.
scons: `build/user/cuda' is up to date.
scons: `build/user/cwp' is up to date.
scons: `build/user/dellinger' is up to date.
scons: `build/user/ditthara' is up to date.
scons: `build/user/dmerzlikin' is up to date.
scons: `build/user/ediazp' is up to date.
scons: `build/user/effsilva' is up to date.
scons: `build/user/fangg' is up to date.
scons: `build/user/fbroggin' is up to date.
scons: `build/user/fomels' is up to date.
scons: `build/user/fperrone' is up to date.
scons: `build/user/gchliu' is up to date.
scons: `build/user/gee' is up to date.
scons: `build/user/godwinj' is up to date.
scons: `build/user/guojian' is up to date.
scons: `build/user/harlan' is up to date.
scons: `build/user/hpcss' is up to date.
scons: `build/user/hwang' is up to date.
scons: `build/user/hzhu' is up to date.
scons: `build/user/ivlad' is up to date.
scons: `build/user/jeff' is up to date.
scons: `build/user/jennings' is up to date.
scons: `build/user/jingwei' is up to date.
scons: `build/user/jmonsegny' is up to date.
gcc -o build/user/jsun/rtmutil.o -c -O2 -x c -std=gnu99 -Wall -pedantic -fopenmp -DNO_BLAS -Ibuild/include -I/usr/include/tirpc build/user/jsun/rtmutil.c
In file included from build/user/jsun/rtmutil.c:2:0:
build/user/jsun/rtmutil.h:217:6: error: conflicting types for 'itoa'
 void itoa(int n, char *s);
      ^~~~
In file included from build/include/rsf.h:57:0,
                 from build/user/jsun/rtmutil.c:1:
/usr/include/stdlib.h:224:8: note: previous declaration of 'itoa' was here
 char * itoa (int, char *, int);
        ^~~~
build/user/jsun/rtmutil.c:745:6: error: conflicting types for 'itoa'
 void itoa(int n, char *s)
      ^~~~
In file included from build/include/rsf.h:57:0,
                 from build/user/jsun/rtmutil.c:1:
/usr/include/stdlib.h:224:8: note: previous declaration of 'itoa' was here
 char * itoa (int, char *, int);
        ^~~~
scons: *** [build/user/jsun/rtmutil.o] Error 1
scons: building terminated because of errors.
make: *** [Makefile:4: all] Error 2
-bash: sudo: no se encontró la orden

This is the error i get while if i run "make; sudo make install". 
Hope anyone can help me.

**Comment by nicklinyi** [comment]
I think you can delete the `jsun` directory first and then install the package.

**Comment by RosendOcana** [comment]
Thanks a lot for the support !!
How can i do it?
Im new on Cygwin.
________________________________
De: Yi Lin <notifications@github.com>
Enviado: jueves, 14 de junio de 2018 06:30:35 a. m.
Para: ahay/src
CC: RosendOcana; Author
Asunto: Re: [ahay/src] Problem while run "make install" with Madagascar on Cygwin. (#131)


I think you can delete the jsun directory first and then install the package.

**Comment by nicklinyi** [comment]
OK, first delete the whole `$RSFSRC/user/jsun` directory under `$RSFSRC/user`. And then install the madagascar package like you did earlier. Your compile error seems like that some of the codes in `user/jsun` conflicted with some header files of Cygwin. So I think simply deleting the `$RSFSRC/user/jsun` would be the easiest way to solve this.

**Comment by sfomel** [comment]
Fixed in https://github.com/ahay/src/commit/e33009dbb0b67c360e9a5993c6ff1ceae025a93d
