### ISSUE TITLE
compilation issue: build/user/zone/matrixops_2D.h

### ISSUE THREAD

**Issue by pythonmobile** [ahay/src#141]
scons: `build/user/pyang' is up to date.
scons: `build/user/urdaneta' is up to date.
scons: *** [build/user/zone/gendix.h] Implicit dependency `build/user/zone/matrixops_2D.h' not found, needed by target `build/user/zone/gendix.h'.
scons: building terminated because of errors.
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zhichenggeng** [comment]
Fixed in 500726b
