### ISSUE TITLE
Configure scripts fails when `user/poulsonj` directory is missing

### ISSUE THREAD

**Issue by dmitry-kabanov** [ahay/src#142]
**Context.** To build a leaner version of Madagascar and to decrease build time, I remove the `user` directory such that `make` will not spend that much time building programs in there.

**Unexpected behavior.** When the `user` directory is removed, `configure` script fails because of the missing `user/poulsonj` directory:

```
OSError: [Errno 2] No such file or directory: '<path>/madagascar-src/user/poulsonj':
  File "<path>/madagascar-src/SConstruct", line 37:
    conf.CheckAll()
  File "/usr/lib/scons/SCons/SConf.py", line 669:
    ret = self.test(context, *args, **kw)
  File "./framework/configure.py", line 136:
    psp(context) #FDNSI
  File "./framework/configure.py", line 1470:
    cwd=testdir)
  File "/usr/lib/python2.7/subprocess.py", line 711:
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343:
    raise child_exception
------------------------
Done with configuration.
```

If I remove all subdirectories of the `user` directory except the `poulsonj` subdirectory, then `configure` succeeds and consequent `make` build succeeds as well.

**Expected behavior.** Both `configure` and `make` should succeed when `user` directory is removed from the source tree. It allows much faster builds of the core Madagascar functionality (1000 vs 230 seconds).

**Comment by zhichenggeng** [comment]
Hi Dmitry,
According to the `configure.py`, you have to keep `user/poulsonj`. Otherwise, there will be something wrong with the configuring even if you don't need the `psp` package. If you really want to remove the `poulsonj` directory, maybe you can try to comment line 136 `psp(context)` in `framework/configure.py`.
![image](https://user-images.githubusercontent.com/22341194/46214483-ea1d3880-c300-11e8-9a26-22582e639234.png)

**Comment by dmitry-kabanov** [comment]
Hi Zhicheng, thank you for the explanation!

I actually managed to build the compact version of Madagascar by removing `book` and `user` directories (except `user/poulsonj` subdirectory).
The build time went down from 20 mins to ~1 min (for 1-core serial build), which is what I wanted.

It is a bit unexpected that the Madagascar build depends  on the `user` code :-)
What is this PSP software, by the way?
If I google for `psp madagascar`, then I can find only some Sony Playstation Madagascar game :-)

**Comment by sfomel** [comment]
PSP is parallel sweeping preconditioner, a specialized code from Jack Poulson.

I have made a change to ignore it if user/poulsonj is not present: https://github.com/ahay/src/commit/6d69d7c6f4036f98bf970164cc85b3f33ed77d46

Please update and try again.

**Comment by dmitry-kabanov** [comment]
I have tested it using https://github.com/ahay/src/commit/6d69d7c6f4036f98bf970164cc85b3f33ed77d46.
Both `configure` and `make` steps were successful when the `user` directory was removed from the source tree.

Thank you!
