### ISSUE TITLE
sfpick does not pick the focus point in the semblance-like panel

### ISSUE THREAD

**Issue by lwn625** [ahay/src#144]
Hi guys,

Very new to Madagascar. I am using sfpick to pick the velocity from the result of sfvscan. 

I tried a few examples (nankai data), which are fine. But when I used my dataset, the sfpick does not pick the focus point in the panel. Actually all picks are much smaller. Tried different parameters but did not work.

Any suggestions are appreciated.
Thanks.
![screenshot from 2018-10-08 11-34-58](https://user-images.githubusercontent.com/30406841/46597674-367f2a00-caf2-11e8-9035-4cc78c952887.png)
![qq20181008120448](https://user-images.githubusercontent.com/30406841/46597735-63334180-caf2-11e8-8a37-d38144e65621.jpg)

**Comment by sfomel** [comment]
1. You may want to use **vel0=** parameter, for example **vel0=3000**. See http://ahay.org/blog/2012/08/01/program-of-the-month-sfpick/
2. It looks like there is a typo in the plotting command: **min=0.5** should be **min1=0.5**.

**Comment by lwn625** [comment]
Dear Sergey,

Thank you very much for your kind support.

The problem is solved by using the parameter vel0. I was using v0, which was copied from other people's example scripts. I guess it might be a old version of parameters.

Now I have realised whenever I look at other examples, I should make sure to use the updated parameters.

Thank you again.

Best regards
Weining
________________________________
