### ISSUE TITLE
Unable to compile some certain source code

### ISSUE THREAD

**Issue by liuyoufang** [ahay/src#152]
Hello Madagascar Users,

I have found a series codes developed specifically for Madagascar and would like to try. 
However I have difficulty of compiling the source codes. This is the error message that I am getting:

Internal Error: no cycle found for node build/user/ext_code/sfvelconvert (<SCons.Node.FS.File object at 0x7f9f79885d60>) in state pending

I am not sure what the root cause is maybe with your help we can track it down. 

Thanks
`Y`

This is the SConstruct file:

mport os, sys, re, string
sys.path.append('../../framework')
import bldutil

progs = '''
syn5d
linearevents5d
geom5d
pad5d
reg5d
pocs5d
taper5d
merge5d
decimate
static
pstm
velpstm
zowem
velwem
spbpdn
wavsep
fkfilter
radfilter
convert_to_angle
velconvert
gxsxtomxhx
innerprod
innerprod2
'''

mpi_progs = '''
mpiwem
mpiwem_poynting
mpiewem
mpiewem_poynting
mpivwem
mpivwem_poynting
mpiewem_sep
'''

pyprogs='''
imagesc
svd_complex
svd_complexblk
dotwem
dotwem_poynting
dotewem
dotewem_poynting
lswem
lswem_poynting
lsewem
lsewem_poynting
lsewem_sep
dotwavsep
weights2c
lspstm
'''

pymods='''
'''

try: # distributed version
    Import('env root pkgdir bindir')
    env = env.Clone()
except: # local version
    env = bldutil.Debug()
    root = None
    SConscript('../../system/seismic/SConstruct')

src = Glob('[a-z]*.c')

env.Prepend(CPPPATH=['../../include'],
            LIBPATH=['../../lib'],
            LIBS=[env.get('DYNLIB','')+'rsf',
                  env.get('DYNLIB','')+'rsfsegy'])

mpicc = env.get('MPICC')
for source in src:
    inc = env.RSF_Include(source,prefix='')
    obj = env.StaticObject(source)
    env.Depends(obj,inc)

fftw = env.get('FFTW')
if fftw:
    progs += ''
elif root:
    place += ''
    for prog in Split('zomiso'):
        prog = env.RSF_Place('sf'+prog,None,var='FFTW',package='fftw')
        env.Install(bindir,prog)

mains = Split(progs)
for prog in mains:
    sources = ['M' + prog]
    bldutil.depends(env,sources,'M'+prog)
    env.StaticObject('M'+prog+'.c')
    prog = env.Program(prog,map(lambda x: x + '.o',sources))
    if root:
        env.Install(bindir,prog)

mpi_mains = Split(mpi_progs)
if mpicc and fftw:
    for prog in mpi_mains:
        sources = ['M' + prog]
        bldutil.depends(env,sources,'M'+prog)
        env.StaticObject('M'+prog+'.c',CC=mpicc)
        prog = env.Program(prog,map(lambda x: x + '.o',sources),CC=mpicc)
        if root:
            env.Install(bindir,prog)
else:
    place += mpi_progs
    for prog in mpi_mains:
        prog = env.RSF_Place('sf'+prog,None,var='MPICC',package='mpi')
        if root:
            env.Install(bindir,prog)

######################################################################
# PYTHON METAPROGRAMS (python API not needed)
######################################################################

if root: # no compilation, just rename
    pymains = Split(pyprogs)
    exe = env.get('PROGSUFFIX','')
    for prog in pymains:
        env.InstallAs(os.path.join(bindir,'sf'+prog+exe),'M'+prog+'.py')

######################################################################
# SELF-DOCUMENTATION
######################################################################
if root:
    user = os.path.basename(os.getcwd())
    main = 'sf%s.py' % user

    docs = map(lambda prog: env.Doc(prog,'M' + prog),mains+mpi_mains) + \
           map(lambda prog: env.Doc(prog,'M'+prog+'.py',lang='python'),pymains)
    env.Depends(docs,'#/framework/rsf/doc.py')

    doc = env.RSF_Docmerge(main,docs)
    env.Install(pkgdir,doc)

**Comment by zhichenggeng** [comment]
Maybe you should add the following line:
```
env.Ignore(inc,inc)
```
between
```
obj = env.StaticObject(source)
```
and
```
env.Depends(obj,inc)
```

**Comment by liuyoufang** [comment]
Zhicheng,

Thank you so much. I made a change based on your comments. However I received a new error:

/opt/local/bin/clang -o Mreg5d.o -c -O3 -fopenmp -I/WORK/rsf/include -I/opt/local/include Mreg5d.c
Mreg5d.c:49:6: error: conflicting types for 'cgesdd_'
void cgesdd_(const char *jobz,const int *M,const int *N,sf_complex *Avec,const int *lda,float *Svec,sf_complex *Uvec,const int *ldu,sf_complex *VTvec,const int *ldvt,sf_complex *work,const in...
     ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/clapack.h:369:5: note: 
      previous declaration is here
int cgesdd_(char *__jobz, __CLPK_integer *__m, __CLPK_integer *__n,
    ^
Mreg5d.c:1044:26: warning: incompatible pointer types passing 'sf_complex *' (aka '_Complex float *') to parameter of type '__CLPK_complex *' [-Wincompatible-pointer-types]
  cgesdd_(&jobz, &M, &N, (sf_complex*)Avec, &lda, Svec, (sf_complex*)Uvec, &ldu, (sf_complex*)VTvec, &ldvt, (sf_complex*)work, &lwork, (float*)rwork, (int*)iwork, &info);  
                         ^~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/clapack.h:370:25: note: 
      passing argument to parameter '__a' here
        __CLPK_complex *__a, __CLPK_integer *__lda, __CLPK_real *__s,
                        ^
Mreg5d.c:1044:57: warning: incompatible pointer types passing 'sf_complex *' (aka '_Complex float *') to parameter of type '__CLPK_complex *' [-Wincompatible-pointer-types]
  cgesdd_(&jobz, &M, &N, (sf_complex*)Avec, &lda, Svec, (sf_complex*)Uvec, &ldu, (sf_complex*)VTvec, &ldvt, (sf_complex*)work, &lwork, (float*)rwork, (int*)iwork, &info);  
                                                        ^~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/clapack.h:371:25: note: 
      passing argument to parameter '__u' here
        __CLPK_complex *__u, __CLPK_integer *__ldu, __CLPK_complex *__vt,
                        ^
Mreg5d.c:1044:82: warning: incompatible pointer types passing 'sf_complex *' (aka '_Complex float *') to parameter of type '__CLPK_complex *' [-Wincompatible-pointer-types]
  cgesdd_(&jobz, &M, &N, (sf_complex*)Avec, &lda, Svec, (sf_complex*)Uvec, &ldu, (sf_complex*)VTvec, &ldvt, (sf_complex*)work, &lwork, (float*)rwork, (int*)iwork, &info);  
                                                                                 ^~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/clapack.h:371:69: note: 
      passing argument to parameter '__vt' here
        __CLPK_complex *__u, __CLPK_integer *__ldu, __CLPK_complex *__vt,
                                                                    ^
Mreg5d.c:1044:109: warning: incompatible pointer types passing 'sf_complex *' (aka '_Complex float *') to parameter of type '__CLPK_complex *' [-Wincompatible-pointer-types]
  cgesdd_(&jobz, &M, &N, (sf_complex*)Avec, &lda, Svec, (sf_complex*)Uvec, &ldu, (sf_complex*)VTvec, &ldvt, (sf_complex*)work, &lwork, (float*)rwork, (int*)iwork, &info);  
                                                                                                            ^~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/clapack.h:372:49: note: 
      passing argument to parameter '__work' here
        __CLPK_integer *__ldvt, __CLPK_complex *__work, __CLPK_integer *__lwork,
                                                ^
4 warnings and 1 error generated.
scons: *** [Mreg5d.o] Error 1
scons: building terminated because of errors.

Do you have any idea what is the new problem would be??

@zhichenggeng

**Comment by zhichenggeng** [comment]
Looks like your code defines a function which has the same name as the function from lapack. 
You can modify your `config.py` by setting both `BLAS` and `LAPACK` as `NO` and then reinstall Madagascar. Or you can modify the header file `rsf.h`. It is under /WORK/rsf/include. In `rsf.h`, you can comment the line 
```
#include <Accelerate/Accelerate.h>
```
Don't know if it works because I never run into this kind of problem.

**Comment by liuyoufang** [comment]
@zhichenggeng Thank you so much. I get most of the codes compiled. However I am running into one exception:

Traceback (most recent call last):
  File "/WORK/rsf/bin/sflspstm", line 21, in <module>
    execfile(os.environ['HOME'] +"/rsf/src/config.py")
IOError: [Errno 2] No such file or directory: '/Users/youfangliu/rsf/src/config.py'

What would a IOError be?? Any Idea.

**Comment by zhichenggeng** [comment]
You should change /rsf/src/config.py to the actual path of Madagascar source directory.

**Comment by zhichenggeng** [comment]
@liuyoufang Have you solved your problems?
