### ISSUE TITLE
sfewefd3d_gpu_p2p and sfewefd3d_gpu_mpi

### ISSUE THREAD

**Issue by wyzhang120** [ahay/src#154]
Has anyone tried sfewefd3d_gpu_p2p and sfewefd3d_gpu_mpi contributed by Robin Weiss ($RSFRSC/user/rweiss)?

I compiled and built these two programs with intel/psxe-2017-64-bit and CUDA/10.0.130. However,  at run time, sfewefd3d_gpu_p2p always reports 'floating point exception'; sfewefd3d_gpu_mpi always hangs.

sfewefd2d_gpu, which was developed by the same author, works fine me for me. Since the compiler flags for sfewefd3d_gpu_p2p and sfewefd2d_gpu are the same, so I think sfewefd3d_gpu_p2p should be compiled correctly. But I am not sure where the error for sfewefd3d_gpu_p2p comes from.  

Also, I would appreciate suggestions on how to debug in the SConstruct framework.

**Comment by sfomel** [comment]
If you run "scons" inside the user directory ($RSFSRC/user/rweiss), it should compile the programs locally with debugging flags, which should make them suitable for running through a debugger.

To find the author's email, see $RSFSRC/AUTHORS.txt
