### ISSUE TITLE
error while running scons

### ISSUE THREAD

**Issue by arnabdhara** [ahay/src#157]
Hi,

I tried running the scons file 
http://www.ahay.org/RSF/book/tccs/ortho/orthonine.html

I get the following error:

scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
retrieve(["bend_l1_pmig_enhanc.sgy", "/mnt/d/Madagascar_data/tccs/ortho/orthonine/bend_l1_pmig_enhanc.sgy"], [])
Cannot access proprietary data server
scons: *** [bend_l1_pmig_enhanc.sgy] Error 7
scons: building terminated because of errors.

**Comment by sfomel** [comment]
The dataset used in this example is proprietary and not publicly available.

**Comment by Jaguar101-jr** [comment]
> The dataset used in this example is proprietary and not publicly available.

so is there any replacement from the authors of Madagascar?
