### ISSUE TITLE
Nankai reproducible paper files

### ISSUE THREAD

**Issue by jefbutar** [ahay/src#162]
Hello everyone
I am trying to reproduce the document presented in http://www.ahay.org/RSF/book/data/nankai/paper_html/node3.html but I cannot find the file filter.c for frequency filtering. I was wondering if there is a way to get access to the file?.

**Comment by zhichenggeng** [comment]
You can find it [here](https://github.com/ahay/src/tree/master/book/data/nankai/data)

**Comment by jefbutar** [comment]
Thanks a lot!!
