### ISSUE TITLE
Madagascar 3 - TypeError: in method 'sf_histstring', argument 2 of type 'char const *'

### ISSUE THREAD

**Issue by maxvelasques** [ahay/src#165]
Hi,
I'm trying to use the new Madagascar 3 and Python 3.7 (and swig) with my code that used to work with Python 2.

For example, when I do:

RSF_IN  = sf.Input()
a1 = RSF_IN.axis(1)

I get the following error message:

Traceback (most recent call last):
    a1 = RSF_IN.axis(1);
  File "/madagascar3/lib/python3.7/site-packages/m8r.py", line 631, in axis
    ax['l'] = self.string("label%d" % i)
  File "/madagascar3/lib/python3.7/site-packages/m8r.py", line 1025, in string
    return c_rsf.sf_histstring(self.file,nm.encode('utf-8'))
TypeError: in method 'sf_histstring', argument 2 of type 'char const *'

Am I missing something?

Thanks.

Max Velasques

**Comment by zhichenggeng** [comment]
Fixed in 442027b241c0ac7b8def032befa089b56addb978
