### ISSUE TITLE
Generate large amount synthetic models for FDM 

### ISSUE THREAD

**Issue by tgautam03** [ahay/src#167]
HI, I want to generate around 50k 2D models and then get traces on them. Is there any way I can do that efficiently using loops or somethings else? I want to get models like the ones we get using trimodel in SU. In SU, I am not able to automate the process using loops such that model parameters can be random.

**Comment by sfomel** [comment]
You can use Python loops in SConstruct. For an example of SU-style finite-difference modeling, see **$RSFSRC/book/rsf/su/sulab5/SConstruct** and **$RSFSRC/book/rsf/su/rsflab5/SConstruct**: http://ahay.org/RSF/book/rsf/su/rsflab5.html
