### ISSUE TITLE
sfdd fails on large files

### ISSUE THREAD

**Issue by aaronjgirard** [ahay/src#169]
I have an ascii file with one float value per line that i am attempting to convert to form=native type=float and the first 978750 values are correctly converted, as can be shown in a sfgrey output. The following values are an exact copy of the last section (see image 1). 

However, if I remove the first 978750 values (the correctly plotted part in image 1), then sfdd the next 896250 values (the bad part in image 1), they are converted correctly (see image 2). 

It seems that sfdd is failing on large file converts from ascii to native.
example: 
`< test3.rsf sfdd  form=native type=float | sfput n1=1250 n2=717 d1=.02 d2=.02 | sfgrey color=j | sfpen`

m8r version 2.1-git

![image1](https://user-images.githubusercontent.com/19921391/69570139-71ede980-0f7c-11ea-9788-5e025a11522b.png)
![image2](https://user-images.githubusercontent.com/19921391/69570140-71ede980-0f7c-11ea-816a-2c54a7999308.png)

**Comment by zhichenggeng** [comment]
Hi, I couldn't reproduce this problem. Could you provide some more details, for example, the command lines you used to convert the file and the system of your machine. Besides, if it is possible, could you share the ASCII file with us because there might be something wrong with it.

**Comment by aaronjgirard** [comment]
Thank you for the reply. I have looked into the file and indeed found one value at that location that was not a float, but a string. This must have caused the buffer to fail and fill the rest of the model with the buffer ad infinitum. I am now seeing that sfdd is working in this sense.
