### ISSUE TITLE
error in "vpconvert Fig/*.vpl format=pdf"

### ISSUE THREAD

**Issue by wangweiwei104** [ahay/src#174]
I can use the following command to successfully convert VPL to EPS and EPS to PDF:
`vpconvert Fig/*.vpl format=eps color=y`
`convert Fig/test.eps Fig/test.pdf`
but I can't directly convert VPL to PDF. Why?
` vpconvert Fig/*.vpl format=pdf
Traceback (most recent call last):
  File "/usr/local/madagascar-3.0/bin/vpconvert", line 210, in <module>
    convert(infile,outfile,format,pen,args)
  File "/usr/local/madagascar-3.0/bin/vpconvert", line 158, in convert
    raise RuntimeError('Cannot convert eps to pdf.') 
RuntimeError: Cannot convert eps to pdf.
`

**Comment by sfomel** [comment]
To make it work, you need to install epstopdf or a2ping.

The following fix might also work: https://github.com/ahay/src/commit/baa74377c248c00fd4efd2f2fb92818f1077311f

**Comment by wangweiwei104** [comment]
> To make it work, you need to install epstopdf or a2ping.
> 
> The following fix might also work: [baa7437](https://github.com/ahay/src/commit/baa74377c248c00fd4efd2f2fb92818f1077311f)

Thanks,Fomel. It worked!
