### ISSUE TITLE
Missing dependency rpc/types.h

### ISSUE THREAD

**Issue by mohammad-akhlaghi** [ahay/src#175]
I am trying to install Madagascar on an Arch Linux system, but the configure script crashes with `Fatal missing dependency`. Here is the end of the `config.log` file:

```
scons: Configure: checking for libraries ... 
.sconf_temp/conftest_2.c <-
  |
  |    #include <rpc/types.h>
  |    #include <rpc/xdr.h>
  |    int main(int argc,char* argv[]) {
  |    return 0;
  |    }
  |
gcc -o .sconf_temp/conftest_2.o -c -O2 -x c -std=gnu99 -Wall -pedantic .sconf_temp/conftest_2.c
.sconf_temp/conftest_2.c:2:14: fatal error: rpc/types.h: No such file or directory
    2 |     #include <rpc/types.h>
      |              ^~~~~~~~~~~~~
compilation terminated.
scons: Configure: no
```
I installed `libtirpc-1.2.5`, and it still gave the same error. I inspected the installation path and found that this header is actually in `/usr/include/tirpc/rpc/types.h`, so I ran the configure command like this:
```shell
$ ./configure CPPFLAGS=/usr/include/tirpc/ --prefix=/my/installation/directory
```
and 
```shell
$ export CPPFLAGS=/usr/include/tirpc/
$ ./configure --prefix=/my/installation/directory
```
Both still had no effect and concluded with the same error message.

**Comment by zhichenggeng** [comment]
Hi, the same error occurred before. This is the solution https://sourceforge.net/p/rsf/mailman/message/36719095/. 
You might need to change fedora to arch?

**Comment by mohammad-akhlaghi** [comment]
Thanks, it worked! 

Just one thing: after looking into `framework/configure.py`, I noticed that those lines weren't present, so I just used the statement for `plat['OS'] == 'cygwin'`, and put it after the `if` structure. In other words, I just put these lines after the `text` variable definition (the contents of the test C program):

```
context.env['CPPPATH'] = path_get(context,'CPPPATH',
                                  '/usr/include/tirpc')
LIBS.append('tirpc')
```

But generally, this manual intervention is very inconvenient and prone to bad bugs. isn't it possible to just read standard environment variables like `CPPFLAGS` and `LDFLAGS` (as with the standard configure scripts)?

**Comment by zhichenggeng** [comment]
Thanks for your suggestion. If we want to make Madagascar platform-independent, we have to write some code specific for each platform. If you have some general methods, please feel free to commit to this repo. We are happy to see others' contributions. 
We haven't fixed this known bug because we haven't tested it on Fedora or similar platforms.
