### ISSUE TITLE
Not able to install madagascar, getting error while running ./config

### ISSUE THREAD

**Issue by tgautam03** [ahay/src#180]
Hi I am following the steps of installation as provided but when I run 
`./configure API = c ++, f90, python, matlab, octave --prefix = / home / tushar / rsf2.0`

I get the following error 
```
> checking for Python ... /usr/bin/python
checking Python version ... 2.7.17
checking for RSFROOT ... no

> I am setting RSFROOT to /usr
checking for SCons ... /usr/bin/scons
checking SCons version ... v3.0.1.74b2c53bc42290e911b334a6b44f187da698a668
Running RSFROOT=/usr /usr/bin/scons  config ...
------------------------
>scons: Reading SConscript files ...
checking platform ... (cached) linux [ubuntu]
checking for C compiler ... (cached) gcc
checking if gcc works ... yes
checking if gcc accepts '-x c -std=gnu99 -Wall -pedantic' ... yes
checking for ar ... (cached) ar
checking for libraries ... [u'm']
checking complex support ... yes
checking for X11 headers ... /usr/include
checking for X11 libraries ... /usr/lib/X11
checking for OpenGL ... yes
checking for sfpen ... (cached) xtpen
checking for ppm ... yes
checking for tiff ... yes
checking for GD (PNG) ... yes
checking for GD (GIF) ... yes
checking for plplot ... yes
checking for ffmpeg ... yes
checking for cairo (PNG) ... yes
checking for cairo (SVG) ... yes
checking for cairo (PDF) ... yes
checking for jpeg ... yes
checking for BLAS ... yes
checking for LAPACK ... yes
checking for SWIG ... (cached) /usr/bin/swig
checking for numpy ... (cached) yes
checking API options ... (cached) []
checking for C++ compiler ... (cached) g++
checking if g++ works ... yes
checking if g++ accepts '-std=c++11 -U__STRICT_ANSI__ -Wall -pedantic' ... yes
checking for MPICC ... (cached) yes
checking if /usr/bin/mpicc works ... yes
checking for MPICXX ... (cached) yes
checking if /usr/bin/mpicxx works ... yes
checking for MPIRUN ... (cached) yes
checking for Posix threads ... yes
checking for OpenMP ... yes
checking for CUDA ... (cached) no
checking for FFTW ... yes
checking if FFTW supports threads ... yes
checking for SuiteSparse ... yes
checking for pfft ... no
scons: done reading SConscript files.
usage: scons [OPTION] [TARGET] ...

> SCons Error: no such option: --prefix
------------------------
> Done with configuration.
```
After this there's no folder rsf2.0. I can't understand what's wrong here, I have all dependencies installed.

**Comment by zhichenggeng** [comment]
Did you add space between `--prefix` and `=`?

**Comment by tgautam03** [comment]
Yeah I had by mistake, I removed those spaces but I am still getting some error
>checking for Python ... /usr/bin/python
checking Python version ... 2.7.17
checking for RSFROOT ... /home/tushar/rsf2.0
checking for SCons ... /usr/bin/scons
checking SCons version ... v3.0.1.74b2c53bc42290e911b334a6b44f187da698a668
Running RSFROOT=/home/tushar/rsf2.0 /usr/bin/scons  config ...
------------------------
>scons: Reading SConscript files ...
checking platform ... (cached) linux [ubuntu]
checking for C compiler ... (cached) gcc
checking if gcc works ... yes
checking if gcc accepts '-x c -std=gnu99 -Wall -pedantic' ... yes
checking for ar ... (cached) ar
checking for libraries ... [u'm']
checking complex support ... yes
checking for X11 headers ... /usr/include
checking for X11 libraries ... /usr/lib/X11
checking for OpenGL ... yes
checking for sfpen ... (cached) xtpen
checking for ppm ... yes
checking for tiff ... yes
checking for GD (PNG) ... yes
checking for GD (GIF) ... yes
checking for plplot ... yes
checking for ffmpeg ... yes
checking for cairo (PNG) ... yes
checking for cairo (SVG) ... yes
checking for cairo (PDF) ... yes
checking for jpeg ... yes
checking for BLAS ... yes
checking for LAPACK ... yes
checking for SWIG ... (cached) /usr/bin/swig
checking for numpy ... (cached) yes
checking API options ... (cached) [u'python']
checking for C++ compiler ... (cached) g++
checking if g++ works ... yes
checking if g++ accepts '-std=c++11 -U__STRICT_ANSI__ -Wall -pedantic' ... yes
checking for MPICC ... (cached) yes
checking if /usr/bin/mpicc works ... yes
checking for MPICXX ... (cached) yes
checking if /usr/bin/mpicxx works ... yes
checking for MPIRUN ... (cached) yes
checking for Posix threads ... yes
checking for OpenMP ... yes
checking for CUDA ... (cached) no
checking for FFTW ... yes
checking if FFTW supports threads ... yes
checking for SuiteSparse ... yes
checking for pfft ... no

>scons: warning: Two different environments were specified for target /home/tushar/rsf2.0/include/Makefile,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 19, in <module>

>scons: warning: Two different environments were specified for target m8r.pyc,
	but they appear to have the same action: __pycompile(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 25, in <module>

>scons: warning: Two different environments were specified for target /home/tushar/rsf2.0/lib/python2.7/dist-packages/m8r.py,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 26, in <module>

>scons: warning: Two different environments were specified for target /home/tushar/rsf2.0/lib/python2.7/dist-packages/m8r.pyc,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 26, in <module>

>scons: warning: Two different environments were specified for target /home/tushar/rsf2.0/lib/python2.7/dist-packages/rsf/api.py,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 29, in <module>

>scons: warning: Two different environments were specified for target /home/tushar/rsf2.0/lib/python2.7/dist-packages/rsf/api.pyc,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 30, in <module>

>scons: warning: Two different environments were specified for target /home/tushar/rsf2.0/bin/m8rtest,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 31, in <module>

>scons: warning: Two different environments were specified for target vplot.pyc,
	but they appear to have the same action: __pycompile(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 25, in <module>

>scons: warning: Two different environments were specified for target /home/tushar/rsf2.0/lib/python2.7/dist-packages/vplot.py,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 26, in <module>

scons: warning: Two different environments were specified for target /home/tushar/rsf2.0/lib/python2.7/dist-packages/vplot.pyc,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 26, in <module>

scons: warning: Two different environments were specified for target las.pyc,
	but they appear to have the same action: __pycompile(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 25, in <module>

scons: warning: Two different environments were specified for target /home/tushar/rsf2.0/lib/python2.7/dist-packages/las.py,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 26, in <module>

scons: warning: Two different environments were specified for target /home/tushar/rsf2.0/lib/python2.7/dist-packages/las.pyc,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 26, in <module>

scons: warning: Two different environments were specified for target m8r_wrap.c,
	but they appear to have the same action: $SWIG -o $TARGET ${_SWIGOUTDIR} ${_SWIGINCFLAGS} $SWIGFLAGS $SOURCES
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 70, in <module>

scons: warning: Two different environments were specified for target c_m8r.py,
	but they appear to have the same action: $SWIG -o $TARGET ${_SWIGOUTDIR} ${_SWIGINCFLAGS} $SWIGFLAGS $SOURCES
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 70, in <module>

scons: warning: Two different environments were specified for target m8r_wrap.os,
	but they appear to have the same action: $SHCC -o $TARGET -c $SHCFLAGS $SHCCFLAGS $_CCCOMCOM $SOURCES
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 81, in <module>

scons: warning: Two different environments were specified for target _c_m8r.so,
	but they appear to have the same action: SharedFlagChecker(target, source, env)
$LDMODULE -o $TARGET $LDMODULEFLAGS $__LDMODULEVERSIONFLAGS $__RPATH $SOURCES $_LIBDIRFLAGS $_LIBFLAGS
LibSymlinksActionFunction(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 81, in <module>

scons: warning: Two different environments were specified for target /home/tushar/madagascar2.0/build/lib/_c_m8r.so,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 85, in <module>

scons: warning: Two different environments were specified for target /home/tushar/madagascar2.0/build/lib/c_m8r.py,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 85, in <module>

scons: warning: Two different environments were specified for target /home/tushar/madagascar2.0/build/lib/m8r.py,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 85, in <module>

scons: warning: Two different environments were specified for target /home/tushar/rsf2.0/lib/python2.7/dist-packages/_c_m8r.so,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 89, in <module>

scons: warning: Two different environments were specified for target /home/tushar/rsf2.0/lib/python2.7/dist-packages/c_m8r.py,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 89, in <module>

scons: warning: Two different environments were specified for target vplot_wrap.c,
	but they appear to have the same action: $SWIG -o $TARGET ${_SWIGOUTDIR} ${_SWIGINCFLAGS} $SWIGFLAGS $SOURCES
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 70, in <module>

scons: warning: Two different environments were specified for target c_vplot.py,
	but they appear to have the same action: $SWIG -o $TARGET ${_SWIGOUTDIR} ${_SWIGINCFLAGS} $SWIGFLAGS $SOURCES
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 70, in <module>

scons: warning: Two different environments were specified for target vplot_wrap.os,
	but they appear to have the same action: $SHCC -o $TARGET -c $SHCFLAGS $SHCCFLAGS $_CCCOMCOM $SOURCES
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 81, in <module>

scons: warning: Two different environments were specified for target _c_vplot.so,
	but they appear to have the same action: SharedFlagChecker(target, source, env)
$LDMODULE -o $TARGET $LDMODULEFLAGS $__LDMODULEVERSIONFLAGS $__RPATH $SOURCES $_LIBDIRFLAGS $_LIBFLAGS
LibSymlinksActionFunction(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 81, in <module>

scons: warning: Two different environments were specified for target /home/tushar/madagascar2.0/build/lib/_c_vplot.so,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 85, in <module>

scons: warning: Two different environments were specified for target /home/tushar/madagascar2.0/build/lib/c_vplot.py,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 85, in <module>

scons: warning: Two different environments were specified for target /home/tushar/madagascar2.0/build/lib/vplot.py,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 85, in <module>

scons: warning: Two different environments were specified for target /home/tushar/rsf2.0/lib/python2.7/dist-packages/_c_vplot.so,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 89, in <module>

scons: warning: Two different environments were specified for target /home/tushar/rsf2.0/lib/python2.7/dist-packages/c_vplot.py,
	but they appear to have the same action: installFunc(target, source, env)
File "/home/tushar/madagascar2.0/build/api/python/SConstruct", line 89, in <module>
scons: done reading SConscript files.
scons: Building targets ...
shell_script(["env.sh"], [])
shell_script(["env.csh"], [])
scons: done building targets.
------------------------
>Done with configuration.

**Comment by zhichenggeng** [comment]
I would suggest deleting the build folder under `/home/tushar/madagascar2.0/`.
Even if it doesn't solve the problem, don't worry about that because they are just warnings.
