### ISSUE TITLE
Building error on cuda file: '-DSF_HAS_FFTW': expected a number

### ISSUE THREAD

**Issue by hyviquel** [ahay/src#181]
I am getting the following error when trying to build on ubuntu 18.04 (libfftw3-dev is installed)

> /usr/local/cuda/bin/nvcc -o build/user/pyang/CUDAfbrec.o -c --x=cu -O -DSF_HAS_FFTW -Ibuild/include build/user/pyang/CUDAfbrec.c
> nvcc fatal   : '-DSF_HAS_FFTW': expected a number

is there a way to fix the error or to disable cuda completely when running configure?

(It used to have a tutorial on the wiki which explain how to install madagascar on ubuntu 18.04 but ahay.org seems to be offline)

**Comment by sfomel** [comment]
I cannot reproduce your error with my version of nvcc but perhaps this change could help: https://github.com/ahay/src/commit/c708e48e88221f2c339917e1362e5f17633c75f3

**Comment by hyviquel** [comment]
Fixed it, thank you very much @sfomel !!
