### ISSUE TITLE
sfimage program not installed

### ISSUE THREAD

**Issue by leoevc** [ahay/src#182]
I recently installed Madagascar 3.0 on Ubuntu 16. I'm trying to reproduce the Teapot Dome work. I got the following in the terminal when running sfimage to see the doc:
$RSFROOT/bin/sfimage is not installed.
Check $RSFROOT/share/madagascar/etc/config.py for XINC and XLIBPATH and reinstall if necessary

How do I install the program? Is there a way for install it without having to re-install Madagascar entirely?

**Comment by zhichenggeng** [comment]
Could you provide the `config.py` file, so that we can check which library you are missing?

**Comment by leoevc** [comment]
`ENV = {'PATH': '/usr/local/bin:/opt/bin:/bin:/usr/bin', u'LD_LIBRARY_PATH': u':'}
RSFROOT = '/home/leoevc/procmada'
AR = 'ar'
JPEG = None
OPENGL = None
OPENGLFLAGS = None
OPENGLPATH = None
MPICC = None
MPICXX = None
SPARSEPATH = None
SPARSELIBS = None
FFTW = None
OMP = True
PTHREADS = True
BLAS = None
LAPACK = None
PPM = None
TIFF = None
GD = None
PLPLOT = None
FFMPEG = None
CAIROPNG = None
DYNLIB = u''
CC = 'gcc'
CFLAGS = u'-O2 -x c -std=gnu99 -Wall -pedantic -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fopenmp'
CPPPATH = []
CPPDEFINES = [u'NO_BLAS']
LIBPATH = []
LIBS = [u'm', u'gomp']
LINKFLAGS = [u'-pthread', u'-fopenmp']
XINC = None
API = [u'c++']
CXX = 'g++'
CXXFLAGS = u'-O2 -std=c++11 -U__STRICT_ANSI__ -Wall -pedantic -fopenmp'
F77 = 'gfortran'
FORTRAN = 'gfortran'
F90 = 'gfortran'
JAVAC = 'javac'
CUDA_TOOLKIT_PATH = None
NUMPY = None
SWIG = None`

**Comment by leoevc** [comment]
[config.docx](https://github.com/ahay/src/files/4252743/config.docx)

**Comment by leoevc** [comment]
Sorry for the mess. I'm new at GitHub

**Comment by zhichenggeng** [comment]
You might need to install x11 library. If you are using ubuntu, you can install it by
```
sudo apt-get install libxaw7-dev
```
Then re-configure it and reinstall Madagascar.

**Comment by leoevc** [comment]
Ok thanks. How do I do the re-configuration?? Is it necessary to Uninstall Madagascar before re-installation??

**Comment by zhichenggeng** [comment]
Just follow the installation tutorial from Madagascar's website. 
```
./configure --prefix=/directory/where/you/want/madagascar/installed
```
You don't need to uninstall it first.

**Comment by leoevc** [comment]
How do I know it will install sfimage? I already installed libxaw7-dev. I did the configuration and I just checked the config.py file and it has everything just like before

**Comment by zhichenggeng** [comment]
In the `config.py` file, the value of `XINC` is still `None`?

**Comment by leoevc** [comment]
Yes

**Comment by zhichenggeng** [comment]
Could you also attach the output from the configuration?

**Comment by leoevc** [comment]
Do you mean the output I got in the terminal???

**Comment by zhichenggeng** [comment]
Right.

**Comment by leoevc** [comment]
checking for Python ... /usr/bin/python
checking Python version ... 2.7.12
checking for RSFROOT ... /home/leoevc/procmada
checking for SCons ... /home/leoevc/procmada/bin/scons
checking SCons version ... v3.0.5.a56bbd8c09fb219ab8a9673330ffcd55279219d0
Running RSFROOT=/home/leoevc/procmada /home/leoevc/procmada/bin/scons  config ...
------------------------
scons: Reading SConscript files ...
checking platform ... (cached) linux [ubuntu]
checking for C compiler ... (cached) gcc
checking if gcc works ... yes
checking if gcc accepts '-x c -std=gnu99 -Wall -pedantic' ... yes
checking if gcc accepts '-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64' ... yes
checking for ar ... (cached) ar
checking for libraries ... [u'm']
checking complex support ... yes
checking for X11 headers ... /usr/include
checking for X11 libraries ... /usr/lib/X11
checking for OpenGL ... no

  Optional package: freeglut3-dev
checking for sfpen ... (cached) xtpen
checking for ppm ... no

  Optional package: libnetpbm10-dev
checking for tiff ... no

  sfbyte2tif, sftif2byte, and tiffpen will not be built.

  Optional package: libtiff5-dev
checking for GD (PNG) ... no

  gdpen will not be built.

  Optional package: libgd-dev
checking for plplot ... no

  Optional package: libplplot-dev
checking for ffmpeg ... no

  Optional package: libavcodec-dev
checking for cairo (PNG) ... no

  Optional package: libcairo2-dev
checking for jpeg ... no

  sfbyte2jpg, sfjpg2byte, and jpegpen will not be built.

  Optional package: libjpeg-dev
checking for BLAS ... no

  Optional package: libblas-dev
checking for LAPACK ... no
checking for SWIG ... (cached) no

  Optional package: swig
checking for numpy ... (cached) no

  Optional package: python-dev python-numpy
checking API options ... (cached) []
checking for C++ compiler ... (cached) g++
checking if g++ works ... yes
checking if g++ accepts '-std=c++11 -U__STRICT_ANSI__ -Wall -pedantic' ... yes
checking for MPICC ... (cached) no

  Optional package: libopenmpi-dev
checking for Posix threads ... yes
checking for OpenMP ... yes
checking for CUDA ... (cached) no
checking for FFTW ... no

  Optional package: libfftw3-dev
checking for SuiteSparse ... no

  Optional package: libsuitesparse-dev
scons: done reading SConscript files.
scons: Building targets ...
shell_script(["env.sh"], [])
shell_script(["env.csh"], [])
scons: done building targets.
------------------------
Done with configuration.

**Comment by zhichenggeng** [comment]
The following output means that Madagascar has found X11 headers and libraries.
```
checking for X11 headers ... /usr/include
checking for X11 libraries ... /usr/lib/X11
```
Are you sure in your `config.py`, `XINC` and `XLIBPATH` are still `None`?

**Comment by leoevc** [comment]
Yes. XLIBPATH is not even there.
Maybe I'm confused; the config.py file was supposed to change after running
make
sudo make install
...?

**Comment by zhichenggeng** [comment]
`config.py` file is supposed to be regenerated after configuration.
Could you delete `config.py` and then do configuration again?

**Comment by leoevc** [comment]
I just finished installation by running
`make
sudo make install`

I checked the `config.py` file located at `$RSFROOT/share/madagascar/etc` and now I got the following `XINC = [u'/usr/include']` and `XLIBPATH = [u'/usr/lib/X11']`

Does this mean it's all right?

**Comment by zhichenggeng** [comment]
Yeah. Then you can type `sfimage` to see if it is installed.
It's weird that the `config.py` stays the same when you do reconfiguration the first time.

**Comment by leoevc** [comment]
It is indeed installed. Thanks a lot for your help

**Comment by leoevc** [comment]
Hi everyone!
Regarding to this issue I have a question.

How can I know what specific Ubuntu packages are necessary for installing certain Madagascar programs??
What is the purpose or function of these packages ??

**Comment by sfomel** [comment]
You can find the full list of packages at http://www.ahay.org/wiki/Advanced_Installation#Ubuntu
