### ISSUE TITLE
[BUG] The output of the CRS parameters (RN, RNIP and BETA) appears in Portuguese in sfvfsacrsnh

### ISSUE THREAD

**Issue by Dirack** [ahay/src#183]
:bug: **Bug report**

**Description of the bug**
The output message of the program sfvfsacrsnh (CRS parameters RN, RNIP and BETA) appears in portuguese.

**To Reproduce**
1. Run the [usage example](https://github.com/ahay/src/tree/master/user/dirack/usage_examples/VFSA)
2. The output on the screen will be:
```sh
< dataCube.rsf /home/dirack/madagascar/bin/sfvfsacrsnh m0=5 v0=1.5 t0=1.1 verb=y repeat=2 > crsParameters.rsf
sfvfsacrsnh: Active mode on!!!
sfvfsacrsnh: Command line parameters: 
sfvfsacrsnh: m0=5.000000 v0=1.500000 t0=1.100000 c0=0.500000 temp0=10.000000 repeat=2
sfvfsacrsnh: Input file parameters: 
sfvfsacrsnh: n1=1001 d1=0.004000 o1=0.000000
sfvfsacrsnh: n2=161 d2=0.012500 o2=0.000000
sfvfsacrsnh: n3=401 d3=0.025000 o3=0.000000
sfvfsacrsnh: Parâmetros otimizados:
 RN=2.783287, RNIP=1.187177, BETA=0.005667, SEMB=0.723192
```

3. See error in the expression _Parâmetros otimizados_. That should be in english.

**Expected behavior**
The message should be _Optimized parameters_.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Version 18.04.4

**Additional context**
The problem is in the [line 186 of the Mvfsacrsnh.c file](https://github.com/ahay/src/commit/c59c1f296c08b38efb9a8522196e1038f0654196#r37523322).
That line snippet bellow: 

```c
/* Show optimized parameters on screen before save them */
sf_warning("Parâmetros otimizados:\n RN=%f, RNIP=%f, BETA=%f,SEMB=%f",otrn,otrnip,otbeta,otsemb);
```

**Comment by zhichenggeng** [comment]
Fixed in 5b81dc924ce1ef3e24a92297e7fb98f8154fbb08.

**Comment by zhichenggeng** [comment]
I really like the way you report bugs. 
@sfomel Do you think if we should add a template for issues?

**Comment by Dirack** [comment]
> I really like the way you report bugs.
> @sfomel Do you think if we should add a template for issues?

I have that template, can I do a Pull Request of it? And you could edit it
