### ISSUE TITLE
Unable to reproduce Marmousi2 experiment

### ISSUE THREAD

**Issue by Sh0lim** [ahay/src#190]
Hi,

i have problem reproducing experiment given in http://www.reproducibility.org/RSF/book/data/marmousi2mp/paper_html/node2.html.

Since I cannot fetch model, I've downloaded model manually from https://wiki.seg.org/wiki/AGL_Elastic_Marmousi#Download. Than I changed SConstruct file like:

comment this line
\# Fetch('vp_marmousi-ii.segy',"marm2")

and added
'MODEL_P-WAVE_VELOCITY_1.25m.segy' in line 13 instead 'vp_marmousi-ii.segy'

When i run scons vp.view vpforward.view vpmigration.view I got identical images as in http://www.reproducibility.org/RSF/book/data/marmousi2mp/paper_html/node2.html.
However when I go to the next page, and when I run scons shots.view shot2500.view mutearr.view mutearr2500.view I got only blue images, instead those shot images.

Any Idea how to solve this? I must say that Im new to seismic processing so maybe Im missing something. What I need ultimately is just to save shoot image as any binary raw image and to use it later-on in some algorithm development.

Thank you.

**Comment by zhichenggeng** [comment]
The units in` vp_marmousi-ii.segy` and `MODEL_P-WAVE_VELOCITY_1.25m.segy` are different.
In the first Flow, delete `sfmath out='input*1000'` like the following
```
Flow('vp vp_hdr vp_hfile.txt vp_hfile.bin','MODEL_P-WAVE_VELOCITY_1.25m.segy',
          '''
         sfsegyread tape=$SOURCE tfile=${TARGETS[1]} \
                              hfile=${TARGETS[2]} bfile=${TARGETS[3]} \
        | sfput d1=1.249 o1=0 label1=Depth    unit1=m  \
                    d2=1.249 o2=0 label2=Distance unit2=m  \
        | sfwindow min1=0 max1=2000 min2=0 max2=5000 j1=10 j2=10
        ''')
```

**Comment by Sh0lim** [comment]
@zhichenggeng Thank you, that solved the problem about displaying image. I have some additional questions if you do not mind.
First, Im not aware of any Madagaskar forum page where these kind of questions may be asked. Is there anything like that? Since my question is not quiet related with the bug, it is more general usage question, I believe it is better to have some discussion page.
Related with my previous question, now Im getting right image, but it is colour image. Do you know how to get greyscale?
And also, after I read segy file and model shots, is it possible to store shots in binary file, e.g. to read them in python or matlab? Right now I only see one shot.rsf file, but where are actual shot measurements?
All the best.

**Comment by zhichenggeng** [comment]
@Sh0lim There is a mailing list for Madagascar users:https://sourceforge.net/projects/rsf/lists/rsf-user.
You are welcome to send your questions there.
To obtain greyscale image, you need to turn off the color option in the `Result`. And yes there is a binary file for each rsf file. Using `sfin`, you will be able to find the binary file showing as `in="location of the binary file"`
I recommend you to read through the Madagascar website http://www.ahay.org/wiki/Main_Page. There are a lot of resources on this web.

**Comment by Sh0lim** [comment]
Thank you very much. I'll switch to mailing list for my further questions.
I'm using Madagaskar webpage as my main source of information. Thanks
