### ISSUE TITLE
OpenMp using Madagascar

### ISSUE THREAD

**Issue by seaninho94** [ahay/src#192]
Hi to everyone,

I'm having a lot of problems with omp. I need the omp library for using some Madagascar codes but I can't solve this problem. I read on the Internet how to install omp but it is not working. I have a Mac OS and the clang version 11.0.3, I installed Xcode and Homebrew.
Can someone tell me step by step how can I install the omp library so when I configure Madagascar the OMP checking goes from False to True? 

Thank you very much

**Comment by zhichenggeng** [comment]
Check this issue #149.
If it doesn't solve the problem, please let me know.

**Comment by seaninho94** [comment]
clang-omp cannot be find. I have installed libomp and llvm with Homebrew. When I try to write a simple code like the one in the issue #149 and then I write on my terminal clang-fopenmp omp.c -o omp it gives me an error.
I have to save the omp.c file somewhere in particular?

**Comment by zhichenggeng** [comment]
It works fine on my machine. 
Could you report your error message?
You might want to use the following to compile:
```
clang -fopenmp -L/usr/local/opt/llvm/lib omp.c -o omp
```

**Comment by seaninho94** [comment]
It continues to give me the same error:
clang-10: error: unable to execute command: Executable "ld" doesn't exist!
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)

Maybe I have done some mistakes before, but I have libomp and llvm installed. I saved my omp.c file in the desktop, I have to save it somewhere else?

**Comment by zhichenggeng** [comment]
There is something wrong with your $PATH. It should be
```
export PATH="/usr/local/opt/llvm/bin:$PATH"
```
Open a new terminal and then compile using the following:
```
/usr/local/opt/llvm/bin/clang -fopenmp -L/usr/local/opt/llvm/lib omp.c -o omp
```
It should work without any export

**Comment by seaninho94** [comment]
It continues to give me the same error, seems like it cannot find the omp.c file. Maybe I have made some mistakes creating that file. I used Xcode, opened a new c file and used the same lines that were in #149 and I saved it on my Desktop. Is there some errors in this procedure?

**Comment by zhichenggeng** [comment]
No. It is not about the file. 
https://askubuntu.com/questions/731635/cannot-find-ld-when-non-root-user
You are messing up with your PATH
Check `which ld`

**Comment by seaninho94** [comment]
(base) Crazis-MacBook-Pro:~ Sean$ which ld
/usr/bin/ld

**Comment by zhichenggeng** [comment]
So you have a new terminal and then you use the following command.
```
/usr/local/opt/llvm/bin/clang -fopenmp -L/usr/local/opt/llvm/lib omp.c -o omp
```
You don't need to do anything else before this command.
Is it still giving the same error?

**Comment by seaninho94** [comment]
No I think this time worked, no error messages.
I wrote ./omp and it worked. 
How can I see if now it works even for Madagascar? I have to open Madagascar and do the configuration?

**Comment by zhichenggeng** [comment]
Following #149, you need to configure Madagascar with
```
./configure CC=`which clang` CXX=`which clang++` --prefix=/PATH_INSTALLED
```

**Comment by seaninho94** [comment]
I did the configuration but it gives me again 
checking for OpenMP no

I have attached here all the message that the configuration gives me:

checking for Python ... /opt/miniconda3/bin/python
checking Python version ... 3.7.4
checking for RSFROOT ... /PATH_INSTALLED
checking for SCons ... /Users/Sean/Desktop/Tesi/bin/scons
checking SCons version ... v3.0.5.a56bbd8c09fb219ab8a9673330ffcd55279219d0
Running RSFROOT=/PATH_INSTALLED /Users/Sean/Desktop/Tesi/bin/scons  config ...
------------------------
scons: Reading SConscript files ...
checking platform ... (cached) darwin [19.4.0]
checking for C compiler ... (cached) /usr/local/opt/llvm/bin/clang
checking if /usr/local/opt/llvm/bin/clang works ... yes
checking for ar ... (cached) ar
checking for libraries ... ['m', 'mx']
checking complex support ... yes
checking for X11 headers ... /opt/X11/include
checking for X11 libraries ... /opt/X11/lib
checking for OpenGL ... yes
checking for sfpen ... (cached) oglpen
checking for ppm ... no
checking for tiff ... no

  sfbyte2tif, sftif2byte, and tiffpen will not be built.
checking for GD (PNG) ... no

  gdpen will not be built.
checking for plplot ... no
checking for ffmpeg ... no
checking for cairo (PNG) ... no
checking for jpeg ... no

  sfbyte2jpg, sfjpg2byte, and jpegpen will not be built.
checking for BLAS ... yes
checking for LAPACK ... yes
checking for SWIG ... (cached) no
checking for numpy ... (cached) yes
checking API options ... (cached) []
checking for C++ compiler ... (cached) /usr/local/opt/llvm/bin/clang++
checking if /usr/local/opt/llvm/bin/clang++ works ... yes
checking if /usr/local/opt/llvm/bin/clang++ accepts '-std=c++11 -U__STRICT_ANSI__ -Wall -pedantic' ... yes
checking for MPICC ... (cached) no
checking for Posix threads ... yes
checking for OpenMP ... no
checking for CUDA ... (cached) no
checking for FFTW ... no
checking for SuiteSparse ... no
scons: done reading SConscript files.
scons: Building targets ...
shell_script(["env.sh"], [])
shell_script(["env.csh"], [])
scons: done building targets.

**Comment by seaninho94** [comment]
scons: Configure: checking for OpenMP ... 
.sconf_temp/conftest_20.c <-
  |
  |    #include <omp.h>
  |    int main(void) {
  |    int nt;
  |#pragma omp parallel
  |{
  |    nt = omp_get_num_threads();
  |}
  |    return 0;
  |    }
  |    
/usr/local/opt/llvm/bin/clang -o .sconf_temp/conftest_20.o -c -O2 -fopenmp .sconf_temp/conftest_20.c
/usr/local/opt/llvm/bin/clang -o .sconf_temp/sfconftest_20 -framework Accelerate -fopenmp .sconf_temp/conftest_20.o -lm -lmx
ld: library not found for -lomp
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
scons: Configure: no

This is the message in the config.log file

**Comment by zhichenggeng** [comment]
Are you using bash or zsh?
In your `.bashrc` or `.zshrc`, add the following
```
export PATH="/usr/local/opt/llvm/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/llvm/lib"
export CPPFLAGS="-I/usr/local/opt/llvm/include"
```

**Comment by seaninho94** [comment]
I'm using zsh. Where can I find my .zshrc?
I add those lines to the terminal but it didn't work

**Comment by zhichenggeng** [comment]
Google is your friend
https://www.google.com/search?q=where+is+my+zshrc+file&rlz=1C5CHFA_enUS889US890&oq=where+is+my+zshrc&aqs=chrome.0.0j69i57j0l4.6092j0j7&sourceid=chrome&ie=UTF-8

**Comment by seaninho94** [comment]
I saved those three lines in the .zshrc file but it gives me the same error, the same config.log as before.
I opened the zshrc with nano and saved those 3 lines and done the configuration again.

**Comment by zhichenggeng** [comment]
Try this:
```
./configure CC=`which clang` CXX=`which clang++` LINKFLAGS=/usr/local/opt/llvm/lib
```

**Comment by seaninho94** [comment]
This way gives me this error, it doesn't go on with the configuration do to a fatal error:


checking if /usr/local/opt/llvm/bin/clang works ... no

  Fatal missing dependency
------------------------
Done with configuration.

**Comment by zhichenggeng** [comment]
Can you also provide the error message in `config.log`.

**Comment by seaninho94** [comment]
scons: Configure: checking if /usr/local/opt/llvm/bin/clang works ... 
.sconf_temp/conftest_0.c <-
  |
  |    int main(int argc,char* argv[]) {
  |    return 0;
  |    }
  |
/usr/local/opt/llvm/bin/clang -o .sconf_temp/conftest_0.o -c -O2 .sconf_temp/conftest_0.c
/usr/local/opt/llvm/bin/clang -o .sconf_temp/sfconftest_0 /usr/local/opt/llvm/lib .sconf_temp/conftest_0.o
ld: can't map file, errno=22 file '/usr/local/opt/llvm/lib' for architecture x86_64
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
scons: Configure: no

**Comment by zhichenggeng** [comment]
If you use the previous configure, it also doesn't work?
```
./configure CC=`which clang` CXX=`which clang++`
```

**Comment by seaninho94** [comment]
No not the same, the configuration works in the other case but the check of openmp doesn’t work.. it gives me the error
ld: library not found for -lomp

in the config.log

**Comment by zhichenggeng** [comment]
Sorry. I made a mistake.
Use this one:
```
./configure CC=`which clang` CXX=`which clang++` LINKFLAGS=-L/usr/local/opt/llvm/lib
```

**Comment by seaninho94** [comment]
Ok thank you very much, now the checking is true.. but I still have problems with my Madagascar exercise. It still gives me the same error, telling me to check for OMP in my config.py file

/Users/Sean/Desktop/Tesi/bin/sfomp is not installed.
Check $RSFROOT/share/madagascar/etc/config.py for OMP
and reinstall if necessary.

/Users/Sean/Desktop/Tesi/bin/sfomp is not installed.
Check $RSFROOT/share/madagascar/etc/config.py for OMP
and reinstall if necessary.
scons: *** [vscan.rsf] Error 1
scons: building terminated because of errors.

**Comment by seaninho94** [comment]
I don't understand one thing. I have two Madagascar directories, the one I downloaded directly from the web and another one that is almost empty( the one located in /share directory). For every other command not including omp, the Madagascar directory that I have downloaded from the web works fine( it has all the directories with all the homeworks and data) but when I need omp, the system checks the other directory /share/madagascar and it doesn't work. There is something I can do to bypass this problem?

Thank you for your help and patience, I really appreciate that.

**Comment by zhichenggeng** [comment]
To solve this, there are several things to do.
First, you need to know that there should be two directories for Madagascar. One contains the source code, and the other one is where Madagascar is installed.
Then please check where is your Madagascar installed.
I would recommend you to set an environment variable.
Add the following to your `.zshrc` file and then source this file or open a new terminal.
```
export RSFROOT=$HOME/RSFROOT
```
Don't forget to actually create this directory.
After this, if you do 
```
./configure CC=`which clang` CXX=`which clang++` LINKFLAGS=/usr/local/opt/llvm/lib
```
in the output, you should find
```
checking Python version ... 3.7.4
checking for RSFROOT ... /Users/Sean/RSFROOT
checking for SCons ... /Users/Sean/Desktop/Tesi/bin/scons
checking SCons version ... v3.0.5.a56bbd8c09fb219ab8a9673330ffcd55279219d0
```
Then you need to reinstall Madagascar.
When the installation is finished, don't forget to follow the instruction to source the corresponding `env.sh`

**Comment by seaninho94** [comment]
What if I'm using bash? I changed yesterday because something was wrong with zsh.
The setting of the variable RSFROOT  and the export line you send me need to be written in the .zshrc or .bashrc file?

**Comment by zhichenggeng** [comment]
Then it should be in `.bashrc`

**Comment by seaninho94** [comment]
How can I set the environment variable? With setenv or with export?

**Comment by zhichenggeng** [comment]
export

**Comment by seaninho94** [comment]
I have to set RSFROOT as the path for the directory where Madagascar is installed? And I have to leave in the file the other export lines you wrote me yesterday?

**Comment by seaninho94** [comment]
This is what I have written in my .bashrc file, but when I go back to the terminal and run ./configure it gives me the error No such file or directory.
The directory madagascar2 is where I've installed madagascar, I have another directory where there is the source code cloned from GitHub. What I'm doing wrong? The problem here is still that the OpenMP doesn't work for Madagascar 


export RSFROOT=/Users/Sean/Desktop/Tesi/madagascar2/share/madagascar/etc
export RSFROOT=$HOME/RSFROOT
source /Users/Sean/Desktop/Tesi/madagascar2/share/madagascar/etc/env.sh
export DATAPATH=$HOME/data/
export RSFBOOK=$HOME/data/book
export RSFFIGS=$HOME/data/figs

export PATH="/usr/local/opt/llvm/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/llvm/lib"
export CPPFLAGS="-I/usr/local/opt/llvm/include"
