### ISSUE TITLE
OMP using Madagascar

### ISSUE THREAD

**Issue by seaninho94** [ahay/src#193]
Hello,

I was trying to use the geo384s/hw3/nmo and in particular the vstack, which needs the omp to execute. Everything else works fine, but I'm having problems with that. 
I have two Madagascar directories, one created cloning from Github and the other one installed after the first configuration(following the instructions on the main page).
The OMP is working for the first directory(the one cloned with all the codes, homeworks etc) but when I run on the terminal for example vstack from nmo directory it gives me the same error:

need to check for the config.py file and if necessary reinstall( the OMP checking is false)

In the second directory(the one installed after first configuration) I can't do any configuration, if I try to type ./configure it gives me the error: command not found.

How can I solve this problem?
Please help me, I'm stuck here and I cannot go any further with this issue.

Thank you

**Comment by sfomel** [comment]
1. You can disable the OMP dependence in  geo384s/hw3/nmo by simply removing the optional split= parameter from Flow commands.
2. The "command not found" error may refer to "/bin/sh". Do you have it in your system?

**Comment by seaninho94** [comment]
Ok thank you very much, I have one more question. If I want to save the data processed(for example in the nmo directory the vstack.rsf file) what I'm supposed to do? Can I convert the file to seg-y(it tells me that has too many headers) or to numpy? How can I do this?

I would like to save all my processed data step by step

**Comment by sfomel** [comment]
You can convert RSF to SEGY using sfsegywrite http://www.ahay.org/wiki/Guide_to_RSF_file_format#Reading_and_writing_SEG-Y_and_SU_files

To check the error from the script, what is the output of "sfin test.rsf"?

An easy way to import to numpy:

```
>>> import m8r
>>> f = m8r.File('test.rsf')
>>> a = f[:]
>>> type(f)
<class 'm8r.File'>
>>> type(a)
<type 'numpy.ndarray'>
```

**Comment by seaninho94** [comment]
This is the output:  sfin test.rsf
test.rsf:
    in="/var/tmp/test.rsf@"
    esize=4 type=float form=native 
    n1=10          d1=1           o1=0          
    n2=9           d2=1           o2=0          
	90 elements 360 bytes

For segywrite it tells me(in the vstack of nmo case) that there are too many headers, how can I change this? 
For python I need to install something? It seems like it cannot find the file .rsf

**Comment by sfomel** [comment]
For sfsegywrite, it is important to have the right tfile= parameter.

```
sfsegyheader < test.rsf > tfile.rsf
sfsegywrite < test.rsf tfile=tfile.rsf > test.segy
```

**Comment by seaninho94** [comment]
Ok now it works, thank you so much.

I have one last question: I tried the codes in the nmo directory and for example the nmo correction is done only to one particular CMP. How I have to modify the SConstruct to have a nmo correction to all the cmps of the dataset?

**Comment by sfomel** [comment]
The same program should work on a dataset that contains multple CMPs. For examples, see "Used In" section in http://www.ahay.org/RSF/sfnmo.html For example, http://ahay.org/RSF/book/rsf/scons/rsf.html referenced in http://ahay.org/blog/2013/04/08/program-of-the-month-sfnmo/

**Comment by seaninho94** [comment]
Sorry for the mistake, NMO works well with multiple CMPs.
I'm having problems with pradon. How can I extend it to all the cmps and how can I have a nice final image with the multiples attenuated? 

And when I try to visualize the cmps of seismic.segy, so the ones with no processing applied to them, I obtain this image. Why it is so strange?

Thank you very much for the support 
![Screenshot 2020-04-22 at 10 35 12](https://user-images.githubusercontent.com/62284105/80115909-9da1e980-8585-11ea-8ea6-2f05cfc1e377.png)
