### ISSUE TITLE
Opening rsf in jupyter notebook

### ISSUE THREAD

**Issue by KirillSimonov** [ahay/src#195]
Dear authors,

I am new to Madagascar and it is my first usage experiment.
I created synthetic seismic using channels.py recipe and now want to open it in jupyter notebook outside of Madagascar.
I put jupyter notebook in folder with created rsf files nad run the following:
![2020-04-27_13h35_15](https://user-images.githubusercontent.com/45141680/80362872-0e018100-888c-11ea-8328-419f43a2c7a4.png)
It seems like jupyter does not see modules from Madagascar or something else.
Could you please give explanations how I can fix it?
Thank you.

---
Sincerely,
Kirill

**Comment by pplotn** [comment]
Hi!
Actually, the good solution is to configure Madagascar before installation with python environment in which you want to use it.

Reinstall your madagascar
source activate your_env
configure blabla API=python
scons install

After that, your_env should include m8r package

**Comment by KirillSimonov** [comment]
Thank you!
