### ISSUE TITLE
[BUG] installing madagascar on cuda enabled machines

### ISSUE THREAD

**Issue by deckerla** [ahay/src#197]
:bug:  Bug report

**Description of the bug**
Installing madagascar on a cuda enabled machine I discovered a bug related to like 154 of the SConstruct file on $RSFSRC/build/user/chenky

It has to do with the line 
        if string.rfind(cc,'icc') >= 0:

Apparently rfind no longer works with string.

**To Reproduce**

Install madagascar on a cuda enabled machine.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by zhichenggeng** [comment]
Should be fixed in 1f70271
