### ISSUE TITLE
Problem while run  `./configure --prefix=/cygdrive/d/Madagascar/exe` with Madagascar on Cygwin（windows 10）

### ISSUE THREAD

**Issue by beyond1995** [ahay/src#199]
# Problem while run  `./configure --prefix=/cygdrive/d/Madagascar/exe` with Madagascar on Cygwin（windows 10）
`$ ./configure --prefix=/cygdrive/d/Madagascar/exe
checking for Python ... /usr/bin/python
checking Python version ... 2.7.16
checking for RSFROOT ... /cygdrive/d/Madagascar/exe
checking for SCons ... no
Installing SCons ... /cygdrive/d/Madagascar/exe/bin/scons
checking SCons version ... v3.0.5.a56bbd8c09fb219ab8a9673330ffcd55279219d0
Running RSFROOT=/cygdrive/d/Madagascar/exe /cygdrive/d/Madagascar/exe/bin/scons  config ...
------------------------
scons: Reading SConscript files ...
checking platform ... (cached) cygwin [unknown]
checking for C compiler ... (cached) gcc
checking if gcc works ... yes
checking if gcc accepts '-x c -std=gnu99 -Wall -pedantic' ... yes
checking for ar ... (cached) ar
checking for libraries ... [u'm', u'tirpc']
checking complex support ... yes
checking for X11 headers ... /usr/include
checking for X11 libraries ... /usr/lib
checking for OpenGL ... yes
checking for sfpen ... (cached) oglpen
checking for ppm ... yes
checking for tiff ... yes
checking for GD (PNG) ... yes
checking for GD (GIF) ... yes
checking for plplot ... no
checking for ffmpeg ... no
checking for cairo (PNG) ... no
checking for jpeg ... no

  sfbyte2jpg, sfjpg2byte, and jpegpen will not be built.
checking for BLAS ... no
checking for LAPACK ... no
checking for SWIG ... (cached) no
checking for numpy ... (cached) no
checking API options ... (cached) []
checking for C++ compiler ... (cached) g++
checking if g++ works ... yes
checking if g++ accepts '-std=c++11 -U__STRICT_ANSI__ -Wall -pedantic' ... yes
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 19: ordinal not in range(128):
  File "/cygdrive/d/Madagascar/madagascar-3.0/SConstruct", line 42:
    conf.CheckAll()
  File "/cygdrive/d/Madagascar/exe/lib/scons/SCons/SConf.py", line 693:
    ret = self.test(context, *args, **kw)
  File "./framework/configure.py", line 141:
    mpi (context) # FDNSI
  File "./framework/configure.py", line 1123:
    mpicc = context.env.get('MPICC',WhereIs('mpicc', path))
  File "/cygdrive/d/Madagascar/exe/lib/scons/SCons/Util.py", line 795:
    f = os.path.join(d, file)
  File "/usr/lib/python2.7/posixpath.py", line 73:
    path += '/' + b
checking for MPICC ... ------------------------
Done with configuration.
`
This is the error i get while if i run  "./configure " or “make”.
Hope anyone can help me.

**Comment by mexika1312** [comment]
I had the same problem. Check https://github.com/ahay/src/commit/23994dc01dbef879bfa1c228c6d10a686cde62ad Adding those two lines helped me.
