### ISSUE TITLE
Using Matlab in Madagascar

### ISSUE THREAD

**Issue by seaninho94** [ahay/src#200]
Hello, I have already installed Madagascar on my computer but I would like to use the Matlab interface. I tried with ./configure API= but it tells me:
Please install MEX

How can I solve this problem?

**Comment by sfomel** [comment]
The mex program usually comes with Matlab and should be in the same directory as matlab.

Try running "which matlab" and "which mex" to find them in your system.

**Comment by seaninho94** [comment]
Ok I did the configuration and now in my config.py file there is Matlab. What I have to do now? I have to set the Matlab path somewhere?

**Comment by sfomel** [comment]
Run "scons install" and make sure that $RSFROOT/lib is in MATLABPATH and LD_LIBRARY_PATH http://www.ahay.org/wiki/Guide_to_madagascar_API#Compiling_6
