### ISSUE TITLE
Plotting interactive picks

### ISSUE THREAD

**Issue by seaninho94** [ahay/src#202]
I tried to use the sfipick program, and for now I used it for one single CMP in the nmo directory (geo384s/hw3). I saved the picks in a .txt file and then converted this to a RSF file. When I try to plot my picks on the semblance figure, there's something wrong with the axes. I will attach the figure, where the white symbols are my picks but they are not in the right position. How can I change this?

![Screenshot 2020-05-31 at 19 15 00](https://user-images.githubusercontent.com/62284105/83358361-3a208e00-a373-11ea-8547-5fc73685621a.png)

**Comment by jmonsegny** [comment]
It looks like you are not plotting the (x,y) pairs, but x and y values both as x coordinates. If that is the case, try transforming the picks to a complex dataset before plotting using dd type=complex. In this way each pick is treated by the plotting program as a pair of coordinates.

**Comment by seaninho94** [comment]
Thank you for the reply,

I tried with adding dd type=complex and the result was better but non exactly right.
For example these are the value of my picks(time and velocity):
0.521739	1.50952	0
0.918261	1.72229	0
1.22435	1.85059	0
1.6487	1.99452	0
2.15652	2.23233	0
3.29043	2.54837	0

But when I plot them on the semblance scan they are not in the correct position(not all of them at least). There is something else I must do? If I want to plot an interpolation line between the points what can I do?
![Screenshot 2020-06-01 at 10 11 08](https://user-images.githubusercontent.com/62284105/83389545-aa212980-a3f0-11ea-8391-8413a0c1d29d.png)

**Comment by jmonsegny** [comment]
What is happening is that your picks plot does not have the same extent as the semblance plot. Vertically, the semblance plot goes from 0 to 4 secs, while the picks plot only goes from the minimum to the maximum t coordinate in the data. To correct this you have to tell "sfgraph" that the minimum and maximum t coordinates are the same as the semblance ones. Add this to the graph parameters:

"min1=0 max1=4". 

I guess that you are using "symbol=+" in your plotting parameters. For plotting the lines between points, make a second plot of the picks omitting this "symbol" parameter, and overlay this plot as well as the other one on top the semblance.

**Comment by seaninho94** [comment]
Thank you very much! One last question.. In this case I selected 6 picks, and in the code, when I convert the txt file, I inserted n2=6 (number of picks). There is a command that allows to set the number of rows to the picks I actually make? So if I do only 3 picks, n2 goes to 3 automatically for example.
And if I want to repeat this procedure for a certain number of CMPs, I have to do a for cycle in the SConstruct file?

**Comment by jmonsegny** [comment]
You could use python to read the picks file, determine the number of coordinates (maybe with the split function) and store this number in a variable. Searching how to count words in a text document using python would be useful. Then you use string substitution to set n2 in the flow:

Flow("... n2=%d.."%npicks)

where npicks is the variable where you stored the number of picks.

I would say that iterating through the picks files is a straightforward way to generate all the velocity plots you need to do. Remember that by using a scons file, you potentially have all python language capabilities.

**Comment by seaninho94** [comment]
Thank you!

I tried to insert the procedure to count the lines in my txt file inside my SConstruct(after the Flow with the creation of the txt file with sfipick) , but when I run it I get the following error:
FileNotFoundError: [Errno 2] No such file or directory: 'picks.txt':
  File "/Users/Sean/Desktop/Tesi/madagascar/book/geo384s/hw3/nmo/SConstruct", line 89:
    file=open("picks.txt","r")

It doesn't find the txt file because I still have to create it with my interactive picking, what I have to change?

**Comment by sfomel** [comment]
You can see an example of solving this problem in $RSFSRC/book/geo384s/hw3/nmo3d/SConstruct

```python
Flow('picks','picks.txt',
     '''
     wc -l |
     sed 's/^/in=$SOURCE data_format=ascii_float n1=3 n2=/' |
     dd form=native | window n1=2
     ''')
```

**Comment by seaninho94** [comment]
I have tried before with those commands (wc and sed), but it gives me this error( even if I try with the nmo3d):
< picks.txt wc -l | sed 's/^/in=picks.txt data_format=ascii_float n1=3 n2=/' | /opt/miniconda3/bin/sfdd form=native | /opt/miniconda3/bin/sfwindow n1=2 > picks.rsf
sfwindow: build/api/c/file.c: No in= in file in: No such file or directory
scons: *** [picks.rsf] Error 1
scons: building terminated because of errors.

I have to install something in order to use the wc and sed commands?

**Comment by sfomel** [comment]
Apparently, wc on a Mac leaves blank spaces before the number. 

I believe I have fixed it here:  https://github.com/ahay/src/commit/5432d0e8a31cb4cac66a776530a9587691df37fa

**Comment by seaninho94** [comment]
Thank you very much, now it works fine. 
But I have a question: in the picks file (talking about the nmo3d example) there are only saved the picks I made. When I go on with the nmo correction, should I do an interpolation of the picks or it's ok if I use only the picks file?
If I need an interpolation, how can I do it?

**Comment by seaninho94** [comment]
In any case, it's the sfpick(the automatic one) sufficiently accurate? Because in terms of time it's very convenient, and if it works well I will use this instead of the interactive one

**Comment by sfomel** [comment]
Yes, you need to interpolate. This part of the script applies smooth interpolation:

```python
Flow('vpick','picks vscan',
     'transp | linear pattern=${SOURCES[1]} rect=5 sort=y')
```

If automatic picking (sfpick) works well for your data, you don't have to use manual picking.
