### ISSUE TITLE
Compiling CUDAfbrec.c [BUG]

### ISSUE THREAD

**Issue by andrei-geophysicist** [ahay/src#206]
:bug:  Bug report

**Description of the bug**

make statement
Error compiling CUDAfbrec.c
OS: Ubuntu
Version: 18.04.4

make
...
/usr/local/cuda/bin/nvcc -o build/user/pyang/CUDAfbrec.o -c --x=cu -O -DSF_HAS_FFTW -I/usr/include/suitesparse -Ibuild/include build/user/pyang/CUDAfbrec.c
nvcc fatal   : '-DSF_HAS_FFTW': expected a number
scons: *** [build/user/pyang/CUDAfbrec.o] Error 1
scons: building terminated because of errors.
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

**Solution**

edit file build/user/pyand/Sconstruct and include zero '0' after option -O
...
# 4. compiling CUDA programs
...
        cflags = env.get('CUDAFLAGS') +' -O'
...

make clean
make

**Comment by sfomel** [comment]
Fixed: https://github.com/ahay/src/commit/c708e48e88221f2c339917e1362e5f17633c75f3
