### ISSUE TITLE
Common shot gather

### ISSUE THREAD

**Issue by seaninho94** [ahay/src#209]
Hi, I have a question about the sorting into CSG. 
Is this the correct script for generating and visualizing a Common Shot Gather:

# Window 1000th shot gather (fldr)
Flow('masky','tparacdp',
     'headermath output=fldr | mask min=1000 max=1000')
Flow('shot','paracdp masky','headerwindow mask=${SOURCES[1]}')

Result('shot',
       '''
       pow pow1=2 |
       grey title="Shot 12" wheretitle=t wherexlabel=b
       ''')

I was trying to save a CSG, convert it to the segy format and then into numpy arrays, I tried with a for cycle (because I have 1000 shots) but the .npy files generated were all the same. 
I have to change something in the script?

**Comment by Dirack** [comment]
@seaninho94, check the range of your mask. You're using min=1000 and max=1000. I do believe you should offer a larger range to the program
