### ISSUE TITLE
Fatal missing dependency

### ISSUE THREAD

**Issue by BoDoNgAhAi** [ahay/src#232]
**Description of the bug**
Hello, 
I wanted to install madagascar-3.1.1 version in ubuntu-20.04 LTS with gcc-10.2 g++-10.2. But I have faced this issue below.
![Screenshot from 2020-12-05 22-55-30](https://user-images.githubusercontent.com/49978120/101246260-19cff280-374d-11eb-9858-fc04072a4aea.png)

And in config.log file:
```
file /home/mc/madagascar-3.1.1/SConstruct,line 47:
	Configure(confdir = .sconf_temp)
scons: Configure: checking platform ... 
scons: Configure: (cached) linux [ubuntu]

scons: Configure: checking for C compiler ... 
scons: Configure: (cached) gcc

scons: Configure: checking if gcc works ... 
.sconf_temp/conftest_0.c <-
  |
  |    int main(int argc,char* argv[]) {
  |    return 0;
  |    }
  |
gcc -o .sconf_temp/conftest_0.o -c -O2 .sconf_temp/conftest_0.c
gcc -o .sconf_temp/sfconftest_0 .sconf_temp/conftest_0.o
scons: Configure: yes

scons: Configure: checking if gcc accepts '-x c -std=gnu17 -Wall -pedantic' ... 
.sconf_temp/conftest_1.c <-
  |
  |    int main(int argc,char* argv[]) {
  |    return 0;
  |    }
  |
gcc -o .sconf_temp/conftest_1.o -c -O2 -x c -std=gnu17 -Wall -pedantic .sconf_temp/conftest_1.c
scons: Configure: yes

scons: Configure: checking for ar ... 
scons: Configure: (cached) ar

scons: Configure: checking for libraries ... 
.sconf_temp/conftest_2.c <-
  |
  |    #include <rpc/types.h>
  |    #include <rpc/xdr.h>
  |    int main(int argc,char* argv[]) {
  |    return 0;
  |    }
  |
gcc -o .sconf_temp/conftest_2.o -c -O2 -x c -std=gnu17 -Wall -pedantic -I/usr/include/tirpc .sconf_temp/conftest_2.c
gcc -o .sconf_temp/sfconftest_2 .sconf_temp/conftest_2.o -lm -ltirpc
/bin/ld: cannot find -ltirpc
collect2: error: ld returned 1 exit status
scons: Configure: no
```

According to the config.log file, the gcc cannot find -ltirpc. I searched through internet to find solution for this but did not find any useful information. Could you help me to fix this problem? I am  a newbie of Ubuntu OS.
Thank you for your time and consideration.

- OS: [Ubuntu]
 - Version [10.04 LTS]

**Comment by zhichenggeng** [comment]
Please install `libtirpc-dev` first. You can use the following command
```
sudo apt-get install libtirpc-dev
```

**Comment by BoDoNgAhAi** [comment]
It works! Thank you.

**Comment by BoDoNgAhAi** [comment]
I would like to report another problem. After installing the madagascar, sfpen and sfimage commands working fine but when I exit the terminal then open it again and write them they do not work. The terminal shows `sfpen: command not found`. I followed issue #182 and after reinstalled the program it works fine then the commands do not work again as I mentioned above. I checked config.py and there are XINC and XLIBPATH.
![Screenshot from 2020-12-05 22-55-30](https://user-images.githubusercontent.com/49978120/101278508-a387ca80-37f6-11eb-977f-5d9a7e33737f.png)
I dont understand why it is occuring. 

Is there other guidance or tutorial for beginners like video or pdf files with step by step guidance? I followed tutorial on ahay.org but it is a bit complicated for me as I noob for programming. 

Thank you for your understanding.

**Comment by zhichenggeng** [comment]
I wonder if only `sfpen` or `sfimage` doesn't work or all commands related to Madagascar don't work.

**Comment by BoDoNgAhAi** [comment]
I followed the instruction of installation and checked the commands in. For instance: 
```
sfin
sfattr
sfspike
sfbandpass
sfwiggle
```
All these commands are working fine, but when I check this `sfspike n1=1000 k1=300 > spike.rsf`the terminal doesnt show anything. It suppose to be show dimensional list. 
![Screenshot from 2020-12-07 12-25-32](https://user-images.githubusercontent.com/49978120/101309502-8bac5700-3887-11eb-8ece-5a7b79ac122f.png)

Also, following commands does not work, except one command:
![Screenshot from 2020-12-07 12-30-15](https://user-images.githubusercontent.com/49978120/101309754-11c89d80-3888-11eb-8346-b1c48aa142f7.png)
