### ISSUE TITLE
Label axis sfgrey

### ISSUE THREAD

**Issue by seaninho94** [ahay/src#233]
Hi to everyone! Is it possible to change one of the axis, so instead of for example a several number of traces (from 1 to 1000) there is the offset that goes from 1 to 5 for the first 50 traces, and then again from 1 to 5 for the traces between 50 and 100 and so on?
So when I plot for examples three gathers together on top I don't have the increasing number of traces (from 1 to 150) but the offset of every gather (so from 1 to 5 for the first one, from 1 to 5 for the second one and same thing for the third one).

Please help me!

**Comment by sfomel** [comment]
The only way to do that is to create three separate plots and to put them side by side.

```python
Result('plot','plot1 plot2 plot3','SideBySideAniso')
```

in SConstruct or

```bash
vppen yscale=3 vpstyle=n gridnum=3,1 plot1.vpl plot1.vpl plot1.vpl > Fig/plot.vpl
```

on the command line.
