### ISSUE TITLE
Compilation Error | Need Urgent Help!!

### ISSUE THREAD

**Issue by noob-6122** [ahay/src#244]
:bug:  Bug report
Description of the bug:
	Compilation error in build/user/jsun/lowrank.cc in ubuntu
How to reproduce the bug
	./configure --prefix=/some/dir API=fortran-90
[report_configure.pdf](https://github.com/ahay/src/files/7091964/report_configure.pdf)

	make
[report.pdf](https://github.com/ahay/src/files/7091967/report.pdf)

Compiling it seperately also produce the same error
g++ -o build/user/jsun/lowrank.o -c -O2 -std=gnu++17 -U__STRICT_ANSI__ -Wall -pedantic -fopenmp -DSF_HAS_FFTW -Ibuild/include build/user/jsun/lowrank.cc
[reportcommandout by EasePDF.pdf](https://github.com/ahay/src/files/7091831/reportcommandout.by.EasePDF.pdf)

**Comment by sfomel** [comment]
Thank you for the detailed report. It looks like this bug was corrected in the current development version: https://github.com/ahay/src/commit/af3d12b055513e42e8a25f4329d4a6a7577bfa8f#diff-2b02767e27069cc1362e864d9c8427e01d4a6a7cb847b0aac06ce16ce65806ea
