### ISSUE TITLE
[BUG]converting rdf file to numpy array

### ISSUE THREAD

**Issue by vira12x** [ahay/src#267]
:bug:  Bug report
Is it possible to convert .rsf file to numpy array, I have 2d data
I tried it as follows

import m8r as sf
import numpy as np
data=sf.Input('input.rsf')

But it doesnot give data, can anybody suggest how to get data from .rsf format

**Comment by sfomel** [comment]
One way to do it is

```python
rsf = sf.File('input.rsf') # rsf has type m8r.File
data = rsf[:]   # data has type numpy.ndarray
```
