### ISSUE TITLE
how to make a velocity model

### ISSUE THREAD

**Issue by chiseo36** [ahay/src#268]
I want to make a velocity model, where the first layer has velocity 3.5km/sec, thickness 5km,second layer has velocity 5km/sec, thickness 4km and third layer has velocity 5.5km/sec,thickness 4km

lateral distance from 0 to 100 kilometer.

I tried in this way but I donot know if i am doing correct

Flow('v1',None,'spike n1=500 n2=1000 d1=10 d2=10 mag=3500')
Flow('v2',None,'spike n1=400 n2=1000 d1=10 d2=10 mag=5000')
Flow('v3',None,'spike n1=550 n2=1000 d1=10 d2=10 mag=5500')
Flow('vel','v1 v2 v3','cat axis=1 ${SOURCES[1:3]} | smooth rect1=3 |put o1=0 | put d2=10)

I hope experts may help me overcoming this problem.

**Comment by sfomel** [comment]
Your method looks fine. You can also check out sfunif2: https://reproducibility.org/blog/2013/10/03/program-of-the-month-sfunif2/
