### ISSUE TITLE
.rsf to .su

### ISSUE THREAD

**Issue by acse-wz19** [ahay/src#270]
Hi,
When i want to convert the 3d rsf data generated by myself to su file, I can not find any instruction to generate the tfile, the header file need in the function sfintbin. Do you know how to generate the tfile according to my 3d data like  n1=7051 n2=324 n3=100?

**Comment by sfomel** [comment]
You can use <tt>sfsegyheader</tt>. See https://www.reproducibility.org/wiki/Guide_to_RSF_file_format#Reading_and_writing_SEG-Y_and_SU_files

A quick example is here (segywrite can be replaced by suwrite): https://www.reproducibility.org/RSF/book/rsf/su/rsfreadwrite.html
