### ISSUE TITLE
question for shot to CMP

### ISSUE THREAD

**Issue by acse-wz19** [ahay/src#272]
if I generate synthetic data，how could I convert the shot gather in to CMP？Is there any example suitable for this situation？

**Comment by sfomel** [comment]
For regularly sampled data, you can use **sfshot2cmp** https://reproducibility.org/RSF/sfshot2cmp.html

**Comment by acse-wz19** [comment]
Thanks for your reply！I will try this function.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Sergey Fomel ***@***.***>
发送时间: Sunday, August 28, 2022 11:59:21 PM
收件人: ahay/src ***@***.***>
抄送: Zhang, Weilin ***@***.***>; Author ***@***.***>
主题: Re: [ahay/src] question for shot to CMP (Issue #272)


This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



For regularly sampled data, you can use sfshot2cmp https://reproducibility.org/RSF/sfshot2cmp.html

―
