### ISSUE TITLE
error:from rsf.recipes.beg import server

### ISSUE THREAD

**Issue by acse-wz19** [ahay/src#273]
retrieve(["vp.asc", "qp.asc", "vp.asc", "qp.asc"], [])
Cannot access proprietary data server
scons: *** [vp.asc] Error 7
scons: building terminated because of errors.

**Comment by acse-wz19** [comment]
Can you explain it a little bit what the serve is ? or how can I get access to the data server of Madagascar to download the data?

**Comment by acse-wz19** [comment]
sorry for mistyping 'server' to 'serve'

**Comment by sfomel** [comment]
It means what it says. The data are proprietary and cannot be publicly shared.

**Comment by acse-wz19** [comment]
sorry, I forgot to add one command line Fetch(['vp.asc','qp.asc'],'marmq',server).

**Comment by acse-wz19** [comment]
this means I can get the data from the server, right?

**Comment by sfomel** [comment]
No, if the data server is proprietary, you cannot download data from it. Only data from the public server are publicly available.

This means that you cannot reproduce the computation in the example, but you can still study the data flow in SContruct and try applying it to your own data.

**Comment by acse-wz19** [comment]
Great! Thanks for your reply.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Sergey Fomel ***@***.***>
发送时间: Monday, November 21, 2022 6:31:39 PM
收件人: ahay/src ***@***.***>
抄送: Zhang, Weilin ***@***.***>; Author ***@***.***>
主题: Re: [ahay/src] error:from rsf.recipes.beg import server (Issue #273)


This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



No, if the data server is proprietary, you cannot download data from it. Only data from the public server are publicly available.

This means that you cannot reproduce the computation in the example, but you can still study the data flow in SContruct and try applying it to your own data.

―
