### ISSUE TITLE
when running reproducible example in $RSFSRC/book/tccs/lowrank/impers, the results are not reproduceble

### ISSUE THREAD

**Issue by acse-wz19** [ahay/src#277]
when  I run this example, and plot the results of low rank approximation. Nothing shows on my screen,
![image](https://user-images.githubusercontent.com/56032987/203502363-15e494af-7122-46b8-85bc-6378a69398e4.png)

**Comment by acse-wz19** [comment]
![image](https://user-images.githubusercontent.com/56032987/203503770-0fa11f05-47d3-4a0a-a385-b854cc3b9f1c.png)

**Comment by zhichenggeng** [comment]
https://github.com/ahay/src/issues/276
