### ISSUE TITLE
two step low rank approximation method is not work, urgent help!!!

### ISSUE THREAD

**Issue by acse-wz19** [ahay/src#278]
The codes Misolr2.cc and Mfftwave2.cc can run but do not work, and I reproduce this using Matlab. The result of Matlab codes is the same as the result of the Madagascar example, and can you help me understand why this is not working? I am looking forward to your reply. If you need it, I can also upload my Matlab code.

**Comment by zhichenggeng** [comment]
Could you provide the code example?

**Comment by zhichenggeng** [comment]
https://github.com/ahay/src/issues/276
