### ISSUE TITLE
`sfomp` is unsequential

### ISSUE THREAD

**Issue by kerim371** [ahay/src#279]
Hi,

I was trying to compute velscans and do auto picking using OpenMP:
```
!sfvscan < {raw_deghost_gain_dip_cdp} offset={cdp_offsets} \
  v0={v0} dv={dv} nv={nv} semblance=y half=n |\
  sfmutter inner=y x0={mute_x0} v0={mute_v0} t0={mute_t0} half=n |\
  sfpick rect1={rect1} back=y > {vnmo_auto_rsf}
```

The result looks like on the pic:
![image](https://user-images.githubusercontent.com/43808863/207163276-3a6b7cdc-0611-46bb-a71b-1ee54c5058fd.png)

As I have 8 threads the velocity model is splited by 8 series.

I guess this behaviour was made intesionally as unsequenced execution works faster.

If so how can I then resort the velocity model?

**Comment by sfomel** [comment]
It may help to use rect2= parameter in <tt>sfpick</tt>: https://reproducibility.org/blog/2012/08/01/program-of-the-month-sfpick/
