### ISSUE TITLE
`sfintbin` applied recurively lead to 3rd dimension growth

### ISSUE THREAD

**Issue by kerim371** [ahay/src#280]
:bug:  Bug report

To sort data I use `sfintbin`.
For example for some reason I sort data recursively, i.e.:
```
sfintbin yk=cdp xk=cdpt head=header_int.rsf < s.rsf > tmp1.rsf
sfintbin yk=cdp xk=cdpt head=header_int_cdp.rsf < tmp1.rsf > tmp2.rsf
```
Then we can see that `tmp2` third dimension has grown by one. 
If `tmp1.rsf n3=10 o3=1`, then will become `tmp2.rsf n3=11 o3=0`.

The similar behaviour we can see when doing sorting by `fldr` and then by `cdp`. 
The resulted `fldr-cdp-sorted` data's 3rd dimension will be begger than `cdp-sorted` data.

**To Reproduce**

1. Read any SEGY file and prepare `header_int.rsf` file and also sort it by cdp to get `header_int_cdp.rsf`
2. Sort original seismic file first time by `yk=cdp xk=cdpt` (or `yk=ep xk=offset` or use any other combination) and save the result to `tmp1.rsf`
4. Sort `tmp1.rsf` by the same two keys and save to `tmp2.rsf`
5. Using `sfin` compare the 3rd dimenstion's size and origin of these two files: `tmp1.rsf` and `tmp2.rsf`

**Expected behavior**

If binning is supposed to work as seismic sorting I expect the third dimension must stay the same.

**Screenshots**

![image](https://user-images.githubusercontent.com/43808863/215341096-81edac06-d9c3-4cc6-9d00-ff83abd10a64.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 
 - Version 20.04

**Comment by sfomel** [comment]
Notice that the value of **o3** changed from **o3=1** to **o3=0.**  That is probably because some traces with missing information have **cdp** set to 0. 

Possible solutions:
1. Run sfintbin using ymin=1
2. Use sfheadersort for sorting before sfintbin https://www.reproducibility.org/wiki/Guide_to_madagascar_programs#sfheadersort

**Comment by kerim371** [comment]
@sfomel hi,



> 1. Run sfintbin using ymin=1

That the solution I made, that works.



> That is probably because some traces with missing information have **cdp** set to 0.

If I understand correctly all the trace header information should be stored in `header_int.rsf` and in its cdp sorted variant `header_int_cdp.rsf`. For the future reference I made a screenshots from `sfheaderattr` command. If possible please comment this. For example I can't understand what means `0 @ 1` or `1 @ 0` in `min` column:
![image](https://user-images.githubusercontent.com/43808863/225755666-186d3343-6433-45d0-9108-846c55b1d8c8.png)
![image](https://user-images.githubusercontent.com/43808863/225755765-3810a225-7af0-4e76-8ad7-fffbf28128b9.png)

**Comment by sfomel** [comment]
0 @ 1 means that the minimum value is 0 and that it occurs at the second trace (traces are counted from 0).

**Comment by kerim371** [comment]
thank you, good to know
