### ISSUE TITLE
[BUG] Fatal error while gcc building src/user/fomel/_byte2tif.c (A immature solution is suggested.)

### ISSUE THREAD

**Issue by cplusv2023** [ahay/src#287]
:bug:  Bug report

**Description of the bug**

I cloned this newest version. After configure, I ran "make && make install", and this gcc building error occured. (Actually it is a linking error). I' ve work out a simple solution but i don't know if it is indeed a proper one. (Though it works.)

The error looks like:
`$ gcc -o build/user/fomels/sfbyte2tif -pthread -fopemp build/user/fonels/_byte2tif.o -lbuild/lib -lrsf -ln -lblas -llapack -lblas -lgonmp-lfftw3f -lfftw3 -lfftw3f_threads -lfftw3_threads -ltiff
`
`
/usr/bin/ld: build/user/fomels/_byte2tif.o: in function 'main' :
`
`
_byte2tif.c: (.text.startup+0x109): undefined reference to 'write_JPEG_file'collect2 : error: ld returned 1 exit status
`
**To Reproduce**

1. Go to this source directory: RSFSRC;
2. ./configure --prefix=/home/myusername/madagascar/RSFROOT;
3. make && make install; 
4. Wait and this error occurs.

**Expected behavior**

When I opened the refered file: "src/user/fomel/_byte2tif.c ", **I found a file  "_jpeg.h" is inclued while it is NOT linked** in:
`$ gcc -o build/user/fomels/sfbyte2tif -pthread -fopemp build/user/fonels/_byte2tif.o -lbuild/lib -lrsf -ln -lblas -llapack -lblas -lgonmp-lfftw3f -lfftw3 -lfftw3f_threads -lfftw3_threads -ltiff
`
and **"-ljped" option is missing**, so I opened the corresponding SConstruct file (src/user/fomel/SConstruct) and **in Line 129** it has:
`
        prog = env.Program('sf'+conv,'_%s.c' % conv,LIBS=libs+[tiff])
`
So I changed **Line 129** as:
`
       prog = env.Program('sf'+conv,['_%s.c' % conv,jpeg_o] ,LIBS=libs+[tiff]+[jpeg])
`
And it works.

**Screenshots**
This is the error and me trying to fix it:
![G 8}7INRMK$78JEQYSC4W~Y](https://user-images.githubusercontent.com/129663479/229351030-d95ce11f-4509-41ae-a611-4f0470dfea4c.png)

And this works:
![~Y5TQ`4XV6WH0G4FCUQ {6G](https://user-images.githubusercontent.com/129663479/229351069-5c50645f-f11f-4757-8d72-b8343dabed2e.png)

**Desktop (please complete the following information):**

- OS: [Ubuntu]
 - Version [22.04]

**Additional context**

By the way, I found that when I used relative path such as "~/madagascar/RSFROOT" to configure, a scons installation error occured. Use absolute path and this would't occur. In previous version relative path was supported though (as I remembered). 
![GSPGI8V~W8YWIXO%~YW74ZV](https://user-images.githubusercontent.com/129663479/229351691-3fc94e6a-53f2-4352-ae32-aef060562ae4.png)

**Comment by sfomel** [comment]
Thank you for reporting this bug. Fixed in https://github.com/ahay/src/commit/2e4cf60b8eb7fb2109203481106f3cc20fa8c763
