### ISSUE TITLE
[BUG] sfdip can not run when using mpi

### ISSUE THREAD

**Issue by Xiaokui824** [ahay/src#288]
I have installed Madagascar in the cluster and tried to call sfdip in C for the dip-angle calculation. There is no problem when using sfdip with a single node. However, when I use mpi and multiple nodes, sfdip runs only on the first node, and the other nodes are always waiting. I wonder if this is why I'm not accurately calling sfdip.

This is my C code:
![image](https://user-images.githubusercontent.com/40201885/233225858-6c4b92c0-17b9-4994-972b-63cac6311b59.png)

**Comment by zhichenggeng** [comment]
I don't think `sfdip2` internally support parallel running. Those programs support multiple nodes execution generally start with `sfmpi`. For running `sfdip2` externally with `mpi`, you can check this: https://reproducibility.org/wiki/Parallel_Computing.

**Comment by Xiaokui824** [comment]
I'm sorry for the delay in my reply. I have tried it, but I still cannot use it. Now, I have implemented manual multi-node operation in the shell script. However, during this process, I encountered a problem where the stored files exceeded the storage capacity. The program generates a temporary file in the /var/tmp folder when reading and writing files. If too many files are generated, it will cause an error. Additionally, since I do not know the names of the generated temporary files during a program operation, I cannot delete them correspondingly. The problem with deleting all temporary files is that it may also delete them from other nodes. Please see the attached error screenshot. 

![1581685156701_ pic](https://github.com/ahay/src/assets/40201885/8404501b-a36e-4066-8da8-2e3f6f77fef9)

I want to know whether I can define the temporary file path myself.
