### ISSUE TITLE
from m2d import * what m2d mean in SConstruct file?

### ISSUE THREAD

**Issue by acse-wz19** [ahay/src#290]
What is the m2d package? and how can I know more about this package? I think this is a Python package in Madagascar, but I do not find any instructions for this package, can you provide some information about this? so that I can better understand it.

**Comment by sfomel** [comment]
The m2d package is in book/Recipes: https://github.com/ahay/src/blob/master/book/Recipes/m2d.py

You can import it in your own SConstruct with

```python
from rsf.recipes import m2d
```

**Comment by acse-wz19** [comment]
Thanks, I learn a lot.

Best

发送自 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Sergey Fomel ***@***.***>
发送时间: Monday, April 24, 2023 9:30:10 PM
收件人: ahay/src ***@***.***>
抄送: Zhang, Weilin ***@***.***>; Author ***@***.***>
主题: Re: [ahay/src] from m2d import * what m2d mean in SConstruct file? (Issue #290)


This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



The m2d package is in book/Recipes: https://github.com/ahay/src/blob/master/book/Recipes/m2d.py

You can import it in your own SConstruct with

from rsf.recipes import m2d

―
