### ISSUE TITLE
https://reproducibility.org/data/ not available 

### ISSUE THREAD

**Issue by AliMakiGmail** [ahay/src#295]
Hi
kindly, why the link:
https://reproducibility.org/data/
not available.
All Fetch data are going to this link.
re-activate the data link, please.
Regards
Ali M. Al-Rahim
ali.m@sc.uobaghdad.edu.iq

**Comment by sfomel** [comment]
Thank you for reporting this problem. There are some current issues with the data server. As a temporary solution, you can use a different server by setting the RSF_DATASERVER environmental variable. Please try the following:
```
export RSF_DATASERVER=https://fomel.com
```

**Comment by AliMakiGmail** [comment]
I put this statement within env.sh 
export RSF_DATASERVER=https://fomel.com
the Fetch goto https://fonel.com
The flowing error produces:
osboxes@osboxes:~/RSFSRC/book/jlu/spefdecon/rdata$ scons view
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
retrieve(["bin.H", "/home/osboxes/RSFDATA/jlu/spefdecon/rdata/bin.H"], [])
Could not download "/home/osboxes/RSFDATA/jlu/spefdecon/rdata/bin.H" from "https://fomel.com/data/yang/bin.H" 
scons: *** [bin.H] Error 5
scons: building terminated because of errors.

kindly advice

**Comment by AliMakiGmail** [comment]
I put this statement within env.sh
export RSF_DATASERVER=https://fomel.com
the Fetch goto https://fonel.com
The flowing error produces:
***@***.***:~/RSFSRC/book/jlu/spefdecon/rdata$ scons view
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
retrieve(["bin.H", "/home/osboxes/RSFDATA/jlu/spefdecon/rdata/bin.H"], [])
Could not download "/home/osboxes/RSFDATA/jlu/spefdecon/rdata/bin.H" from "
https://fomel.com/data/yang/bin.H"
scons: *** [bin.H] Error 5
scons: building terminated because of errors.

kindly advice

**Comment by sfomel** [comment]
The missing file was restored. Please try again.

**Comment by AliMakiGmail** [comment]
Everything is OK thanks
