### ISSUE TITLE
[FEA] Numpy 2.0.0+ include path

### ISSUE THREAD

**Issue by cplusv2023** [ahay/src#313]
:tada: **Feature request**

**Numpy 2.0.0 API path "numpy/core" is renamed to "numpy/_core" [gh-24634](https://github.com/numpy/numpy/pull/24634).**

Maybe we can simply alter the include dir by replacing
```python
        pythinc.append(os.path.join(numpy_loc,'core','include'))
```
in api/python/SConstruct with
```python
        if int(numpy.__version.split(".")[0]) >=2:
            pythinc.append(os.path.join(numpy_loc,'_core','include'))
        else:
            pythinc.append(os.path.join(numpy_loc,'core','include'))
```

**Comment by sfomel** [comment]
Thank you for the suggestion. The change has been made: https://github.com/ahay/src/commit/0130be529f2902f07e026bc660d6338897a58b1f
